<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.8">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jared Greathouse">
<meta name="dcterms.date" content="2026-09-12">

<title>Difference-in-Differences Is a Synthetic Control With Uniform Weights – Policy Analysis, Data Science, and Causal Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-listing/list.min.js"></script>
<script src="site_libs/quarto-listing/quarto-listing.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-fae04a4dda57acfb7da1e58796bfa73f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7e7f088023de72502c0008de511c2141.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

  window.document.addEventListener("DOMContentLoaded", function (_event) {
    const listingTargetEl = window.document.querySelector('#listing-listing .list');
    if (!listingTargetEl) {
      // No listing discovered, do not attach.
      return; 
    }

    const options = {
      valueNames: ['listing-date','listing-title','listing-author','listing-categories',{ data: ['index'] },{ data: ['categories'] },{ data: ['listing-date-sort'] },{ data: ['listing-file-modified-sort'] }],
      
      searchColumns: ["listing-date","listing-title","listing-author","listing-subtitle","listing-image","listing-description","listing-categories"],
    };

    window['quarto-listings'] = window['quarto-listings'] || {};
    window['quarto-listings']['listing-listing'] = new List('listing-listing', options);

    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  });

  window.addEventListener('hashchange',() => {
    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  })
  </script>
<script>
window.MathJax = {
  tex: {
    macros: {
      defeq: "\\mathrel{\\mathop:}=",
      // Add more macros below as needed
      // R: "\\mathbb{R}",
      // E: "\\mathbb{E}",
      // Var: "\\operatorname{Var}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Policy Analysis, Data Science, and Causal Inference</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://jgreathouse9.github.io"> 
<span class="menu-text">About Jared</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#start-with-parallel-trends" id="toc-start-with-parallel-trends" class="nav-link active" data-scroll-target="#start-with-parallel-trends">Start with parallel trends</a></li>
  <li><a href="#the-same-story-in-optimization-language" id="toc-the-same-story-in-optimization-language" class="nav-link" data-scroll-target="#the-same-story-in-optimization-language">The same story in optimization language</a></li>
  <li><a href="#where-synthetic-control-comes-in" id="toc-where-synthetic-control-comes-in" class="nav-link" data-scroll-target="#where-synthetic-control-comes-in">Where synthetic control comes in</a></li>
  <li><a href="#proposition-99-with-uniform-weights-and-an-intercept" id="toc-proposition-99-with-uniform-weights-and-an-intercept" class="nav-link" data-scroll-target="#proposition-99-with-uniform-weights-and-an-intercept">Proposition 99, with uniform weights and an intercept</a></li>
  <li><a href="#so-what" id="toc-so-what" class="nav-link" data-scroll-target="#so-what">So what?</a></li>
  </ul>
</nav>
    <h5 class="quarto-listing-category-title">Categories</h5><div class="quarto-listing-category category-default"><div class="category" data-category="">All <span class="quarto-category-count">(20)</span></div><div class="category" data-category="QXV0b21hdGlvbg==">Automation <span class="quarto-category-count">(1)</span></div><div class="category" data-category="Q2F1c2FsJTIwSW5mZXJlbmNl">Causal Inference <span class="quarto-category-count">(6)</span></div><div class="category" data-category="RWNvbm9tZXRyaWMlMjBUaGVvcnk=">Econometric Theory <span class="quarto-category-count">(2)</span></div><div class="category" data-category="RWNvbm9tZXRyaWNz">Econometrics <span class="quarto-category-count">(11)</span></div><div class="category" data-category="RXhwZXJpbWVudHM=">Experiments <span class="quarto-category-count">(1)</span></div><div class="category" data-category="R2l0aHVi">Github <span class="quarto-category-count">(1)</span></div><div class="category" data-category="TWFjaGluZSUyMExlYXJuaW5n">Machine Learning <span class="quarto-category-count">(2)</span></div><div class="category" data-category="UHl0aG9u">Python <span class="quarto-category-count">(1)</span></div><div class="category" data-category="U3RhdGlzdGljcw==">Statistics <span class="quarto-category-count">(1)</span></div><div class="category" data-category="V2ViJTIwU2NyYXBpbmc=">Web Scraping <span class="quarto-category-count">(1)</span></div></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Difference-in-Differences Is a Synthetic Control With Uniform Weights</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Econometric Theory</div>
    <div class="quarto-category">Causal Inference</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jared Greathouse </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This is a follow-up to my last excerpt, and (like that one) a preview of my forthcoming book on synthetic control methods.</p>
<div class="epigraph">
<blockquote class="blockquote">
<p>“I think we may be In a different book, on a different page You said you are different but you’re the same” — <a href="https://genius.com/Jhene-aiko-stranger-lyrics"><em>Jhené Aiko</em></a>, “stranger”</p>
</blockquote>
</div>
<hr>
<p>After the <a href="averagesexcp.html">last post</a>, where I showed that the arithmetic mean is really the solution to an optimization problem, somebody asked me a good question: <em>why do people keep saying difference-in-differences (DID) is just synthetic control (SCM) with uniform weights?</em> It is a fair thing to be confused about. The two are usually taught in different classes, with different notation, and DID in particular is almost never presented as an optimization problem at all — it is presented as a table with four cells and a subtraction, justified by parallel trends.</p>
<p>So let me start where everyone already is, with parallel trends. Then I will translate that familiar story into the same optimization problem we solved for the mean last time — only now with the weights held fixed — and show that, told this way, the link to synthetic control is a line of algebra rather than a slogan. At the end I will run the whole thing on Proposition 99 in Python, so you can watch the weights and the intercept do their jobs.</p>
<section id="start-with-parallel-trends" class="level2">
<h2 class="anchored" data-anchor-id="start-with-parallel-trends">Start with parallel trends</h2>
<p>Almost everyone who has met DID has met parallel trends. The setup is two groups, one treated and one not, observed before and after some intervention. DID takes the <em>change</em> in the treated group’s outcome and subtracts the <em>change</em> in the control group’s outcome. If, absent treatment, the two groups’ average outcomes would have moved in parallel, then the control group’s change stands in for the change the treated group would have had anyway, and the leftover — the difference of the two differences — is the treatment effect.</p>
<p>What is parallel trends really saying, though? Set the formula aside for a second. Suppose that on the very first day we look, our treated unit sits about 5 units above the control average. Not because of treatment — nothing has happened yet — but simply because that is where it starts: maybe it is a richer state, a bigger market, a heavier-smoking population. Parallel trends is the claim that this gap of 5 is <em>sticky</em>. On the next day, absent treatment, the treated unit is again about 5 above the controls, in expectation. Ten periods later, still about 5. The two lines may climb, fall, and zig-zag with the business cycle however they like — but the <em>distance between them</em> stays parked at 5, period after period, for as long as no treatment intervenes.</p>
<p>Sit with what that does and does not allow. It does not ask the treated and control groups to be at the same level — they are 5 apart the entire time, and that is fine. It asks only that the 5 never moves. So the treatment, when it finally arrives, is whatever makes the gap <em>depart</em> from 5. If the gap opens up to 32 after the policy, the treatment did the extra 27; the 5 was always going to be there. That one sticky number is the whole ballgame — and, as we are about to see, it is exactly the number the optimization solves for.</p>
<p><a href="#fig-pta-cartoon" class="quarto-xref">Figure&nbsp;1</a> draws both worlds. On the left, the two lines wander all over — up, down, with the cycle — but the distance between them never leaves 5. That is parallel trends. On the right, the two start 5 apart and then drift; the gap grows to 15 for reasons that have nothing to do with any treatment. Both panels are the untreated world, before anyone has been treated. DID is only trustworthy in the world on the left.</p>
<div id="cell-fig-pta-cartoon" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-pta-cartoon" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pta-cartoon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="didexcp_files/figure-html/fig-pta-cartoon-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pta-cartoon-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: What parallel trends assumes, absent treatment: the gap between treated and control is a single sticky number. Left, it stays at 5 (parallel trends holds); right, it drifts off 5 (parallel trends fails).
</figcaption>
</figure>
</div>
</div>
</div>
<p>Write it for a single treated unit and a donor pool <span class="math inline">\(\mathcal{N}_0\)</span> of <span class="math inline">\(N_0\)</span> never-treated units. Let <span class="math inline">\(y_{1t}\)</span> be the treated unit and <span class="math inline">\(\bar{y}_{0t}\)</span> the control-group average at time <span class="math inline">\(t\)</span>. Parallel trends says the expected gap between them is one and the same constant over time, treatment aside:</p>
<p><span class="math display">\[
\mathbb{E}\!\left[\, y_{1t}(0) - \bar{y}_{0t}(0) \,\right] = \beta, \qquad \forall \, t,
\]</span></p>
<p>the same <span class="math inline">\(\beta\)</span> before <em>and</em> after the intervention. This is the assumption that the average untreated outcome evolves in parallel for the two groups; everything DID reports is downstream of it.</p>
<p>Here is the thing I want to flag before we go further, because it is the crux of the question I was asked. In the way DID is almost always taught and applied, this is a <strong>large-<span class="math inline">\(N\)</span></strong> statement. You have many controls, and <span class="math inline">\(\bar{y}_{0t}\)</span> is not really “38 states averaged with weight <span class="math inline">\(1/38\)</span>” in anyone’s mind — it is a sample estimate of a population expectation, <span class="math inline">\(\mathbb{E}[y_t(0) \mid D = 0]\)</span>, the untreated mean in the control population. As the control group grows, the sample average converges to that expectation, and nobody stops to notice that an expectation is itself a weighting. In the <a href="https://doi.org/10.1257/jel.20251650">Baker, Callaway, Cunningham, Goodman-Bacon and Sant’Anna (2026)</a> practitioner’s guide the point is explicit from the first equations: the DID estimand is written with a <em>weighted</em> expectation <span class="math inline">\(\mathbb{E}_\omega[\cdot]\)</span>, and the weights, they note, enter “as part of the definition of the causal parameter” — before you have estimated anything. Large-<span class="math inline">\(N\)</span> asymptotics just let you fold them into the word “expectation” and stop looking. We do not usually need to treat the weights as objects. That does not mean they are not there.</p>
</section>
<section id="the-same-story-in-optimization-language" class="level2">
<h2 class="anchored" data-anchor-id="the-same-story-in-optimization-language">The same story in optimization language</h2>
<p>Now let me translate all of that into the language of the <a href="averagesexcp.html">last post</a>, where every summary statistic turned out to be an argmin. The bridge is one identity we proved there: a (weighted) mean is the constant that minimizes (weighted) squared error. In the population,</p>
<p><span class="math display">\[
\mathbb{E}_\omega[X] = \operatorname*{argmin}_{c \in \mathbb{R}} \; \mathbb{E}_\omega\!\big[(X - c)^2\big] ,
\]</span></p>
<p>and in a sample,</p>
<p><span class="math display">\[
\sum_i \omega_i \, x_i = \operatorname*{argmin}_{c \in \mathbb{R}} \; \sum_i \omega_i \, (x_i - c)^2 .
\]</span></p>
<p>So the weighted expectation the practitioner’s guide puts at the center of DID <em>is</em> an argmin, and the <span class="math inline">\(\omega\)</span> riding on the expectation is the same <span class="math inline">\(\omega\)</span> that weights the squared errors. Translating the notation, the control-group counterfactual is the expectation-side name for a one-parameter least-squares fit:</p>
<p><span class="math display">\[
\underbrace{\mathbb{E}_\omega[\,y_t(0) \mid D = 0\,]}_{\text{expectation notation}}
\;=\;
\underbrace{\operatorname*{argmin}_{c \in \mathbb{R}} \sum_{j \in \mathcal{N}_0} \omega_j \, (y_{jt} - c)^2}_{\text{optimization notation}}
\;\overset{\omega \,=\, 1/N_0}{=}\;
\bar{y}_{0t} .
\]</span></p>
<p>Read left to right it is a population expectation; read right to left it is a weighted mean, which is a weighted argmin, which — at uniform weights — is the plain control average <span class="math inline">\(\bar{y}_{0t}\)</span>. The weights that large-<span class="math inline">\(N\)</span> hid inside the word “expectation” are now out in the open as the coefficients <span class="math inline">\(\omega_j\)</span>. What is left is to put the treated unit and a level back in.</p>
</section>
<section id="where-synthetic-control-comes-in" class="level2">
<h2 class="anchored" data-anchor-id="where-synthetic-control-comes-in">Where synthetic control comes in</h2>
<p>Both methods minimize one and the same object: the least-squares fit of the treated unit’s pre-treatment path to the donors, with an intercept for the level, over weights on the simplex.</p>
<p><span class="math display">\[
\min_{\mathbf{w}, \, \beta} \; \big\| \mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w} - \beta \mathbf{1} \big\|_2^2
\qquad \text{subject to} \qquad
w_j \ge 0, \quad \textstyle\sum_{j \in \mathcal{N}_0} w_j = 1 .
\]</span></p>
<p>Here <span class="math inline">\(\mathbf{y}_1 \in \mathbb{R}^{T_0}\)</span> is the treated unit over the <span class="math inline">\(T_0\)</span> pre-treatment periods, <span class="math inline">\(\mathbf{Y}_0 \in \mathbb{R}^{T_0 \times N_0}\)</span> the donor matrix, <span class="math inline">\(\mathbf{w}\)</span> the donor weights, and <span class="math inline">\(\beta\)</span> an intercept — a level shift, the “5” from the top of the post. This is ordinary least squares with an intercept, over the probability simplex — the same non-negative, sum-to-one constraint the arithmetic mean’s own weights <span class="math inline">\(1/n\)</span> satisfy. Deriving DID from it takes two steps: handle the intercept, then set the weights.</p>
<p><strong>The intercept is a demeaning operator.</strong> The intercept never has to be searched over. For any fixed <span class="math inline">\(\mathbf{w}\)</span>, the best <span class="math inline">\(\beta\)</span> is the one-parameter fit of a single constant to the residual series <span class="math inline">\(\mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w}\)</span>, and by the identity above that constant is the residual’s pre-period average, <span class="math inline">\(\beta^\ast(\mathbf{w}) = \tfrac{1}{T_0} \sum_{t \in \mathcal{T}_1} \big( y_{1t} - (\mathbf{Y}_0 \mathbf{w})_t \big)\)</span>. Substitute it back and <span class="math inline">\(\beta\)</span> disappears into a <em>centering</em> of both sides. Let the demeaning operator be</p>
<p><span class="math display">\[
\mathbf{M} \defeq \mathbf{I}_{T_0} - \tfrac{1}{T_0}\, \mathbf{1}\mathbf{1}^\top ,
\]</span></p>
<p>the <span class="math inline">\(T_0 \times T_0\)</span> matrix that subtracts a vector’s pre-period time-average from each of its entries. Profiling the intercept out of the objective leaves</p>
<p><span class="math display">\[
\min_{\beta} \big\| \mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w} - \beta \mathbf{1} \big\|_2^2
= \big\| \mathbf{M}\mathbf{y}_1 - \mathbf{M}\mathbf{Y}_0 \mathbf{w} \big\|_2^2 .
\]</span></p>
<p>Adding an intercept and demeaning the data are the same operation: <span class="math inline">\(\beta\)</span> absorbs the common level and <span class="math inline">\(\mathbf{M}\)</span> removes it. What remains is a fit of the treated unit to the donors, both in deviations from their pre-period means, over <span class="math inline">\(\mathbf{w}\)</span> on the simplex. Synthetic control solves exactly this — it <em>searches</em> the simplex for the weights that fit best.</p>
<p><strong>Set the weights to <span class="math inline">\(1/N_0\)</span>, and you have DID.</strong> Difference-in-differences does not search. It plants <span class="math inline">\(\mathbf{w}\)</span> at the centroid of the simplex, <span class="math inline">\(w_j = 1/N_0\)</span> for every donor, so <span class="math inline">\(\mathbf{Y}_0 \mathbf{w}\)</span> collapses to the plain control average <span class="math inline">\(\bar{\mathbf{y}}_0\)</span> and only the intercept is left. Write the per-period gap as</p>
<p><span class="math display">\[
g_t \defeq y_{1t} - \bar{y}_{0t}.
\]</span></p>
<p>Its pre-treatment average is DID’s intercept — the same one-parameter least-squares fit as before, with the “data points” now the gaps <span class="math inline">\(g_t\)</span>:</p>
<p><span class="math display">\[
\beta^\ast = \operatorname*{argmin}_{\beta \in \mathbb{R}} \sum_{t \in \mathcal{T}_1} (g_t - \beta)^2.
\]</span></p>
<p>The minimizer is the mean derivation all over again. With <span class="math inline">\(u_t(\beta) = g_t - \beta\)</span>, the chain rule gives each term’s derivative as <span class="math inline">\(2 u_t(\beta) \cdot (-1) = -2(g_t - \beta)\)</span>; summing and setting to zero,</p>
<p><span class="math display">\[
-2 \sum_{t \in \mathcal{T}_1} (g_t - \beta) = 0
\;\;\Longrightarrow\;\;
\sum_{t \in \mathcal{T}_1} g_t - T_0 \beta = 0
\;\;\Longrightarrow\;\;
\beta^\ast = \frac{1}{T_0} \sum_{t \in \mathcal{T}_1} g_t,
\]</span></p>
<p>and the second derivative <span class="math inline">\(2 T_0 &gt; 0\)</span> confirms it is a minimum. So <span class="math inline">\(\beta^\ast\)</span> is just the average pre-treatment gap — the sticky “5” from the top of the post, now estimated from the data — and the counterfactual is the control mean shifted by this one number, <span class="math inline">\(\hat{y}_{1t}(0) = \bar{y}_{0t} + \beta^\ast\)</span>.</p>
<p>That least-squares fit is a <em>model</em> of the gap: it says the gap is one constant plus noise. And this is where parallel trends drops into the same lens. In expectation notation it reads <span class="math inline">\(\mathbb{E}[g_t] = \beta\)</span> for all <span class="math inline">\(t\)</span>; translated, that is the statement that the intercept is stable across the treatment date — the constant that best fits the pre-period gap is the same constant that best fits the post-period gap:</p>
<p><span class="math display">\[
\underbrace{\mathbb{E}[g_t] = \beta \;\; \forall \, t}_{\text{expectation notation}}
\qquad\Longrightarrow\qquad
\underbrace{\operatorname*{argmin}_{\beta} \, \mathbb{E}\!\!\sum_{t \in \mathcal{T}_1} (g_t - \beta)^2
\;=\;
\operatorname*{argmin}_{\beta} \, \mathbb{E}\!\!\sum_{t \in \mathcal{T}_2} (g_t - \beta)^2}_{\text{optimization notation}} .
\]</span></p>
<p>We only ever get to <em>solve</em> the left-hand problem — the post-period gaps <span class="math inline">\(g_t\)</span> for <span class="math inline">\(t \in \mathcal{T}_2\)</span> are unobserved, since they contain the counterfactual we are after. Parallel trends is precisely the license to carry the pre-period solution across the treatment date and use it on the right. This is the “5 never moves” claim written as an optimization: the single constant that minimizes the pre-period squared gap is the same constant that minimizes it afterward. Equivalently, the residual <span class="math inline">\(r_t = g_t - \beta^\ast\)</span> is mean-zero with no time structure — the gap is a flat line at <span class="math inline">\(\beta^\ast\)</span> in expectation, that same sticky number, pre and post alike.</p>
<p>And now the weights and parallel trends are visibly the same conversation. The gap <span class="math inline">\(g_t = y_{1t} - \sum_j w_j y_{jt}\)</span> carries the weights inside it, so whether <span class="math inline">\(\mathbb{E}[g_t]\)</span> is flat is a fact about <span class="math inline">\(\mathbf{w}\)</span>, not about “California and the controls” in the abstract. Change <span class="math inline">\(\mathbf{w}\)</span> and you change the gap, and you change whether its expectation is a constant. The two methods make opposite bets with that lever:</p>
<ul>
<li><strong>DID</strong> fixes <span class="math inline">\(\mathbf{w} = 1/N_0\)</span> and then <em>assumes</em> the resulting gap is flat in expectation. Parallel trends is a hope about a gap you never got to shape.</li>
<li><strong>SCM</strong> <em>chooses</em> <span class="math inline">\(\mathbf{w}\)</span> on the simplex to make the pre-period gap as flat as it can. It buys parallel pre-trends in-sample, by construction, instead of assuming it.</li>
</ul>
<p>So the weights were never a side issue that large-<span class="math inline">\(N\)</span> was right to hide. They are the one lever that decides whether parallel trends is even plausible, and DID’s choice to leave that lever parked at the center of the simplex <em>is</em> its identifying content.</p>
</section>
<section id="proposition-99-with-uniform-weights-and-an-intercept" class="level2">
<h2 class="anchored" data-anchor-id="proposition-99-with-uniform-weights-and-an-intercept">Proposition 99, with uniform weights and an intercept</h2>
<p>Let me show the weights and the intercept in the flesh. I will use Abadie, Diamond and Hainmueller’s canonical Proposition 99 setup: California is treated by the 1989 anti-tobacco law, there are 38 control states, and we observe per-capita cigarette sales from 1970 to 2000. To follow along you’ll want the <code>dataprep</code> helper from my <code>mlsynth</code> package:</p>
<pre class="{shell}"><code>pip install -U git+https://github.com/jgreathouse9/mlsynth.git</code></pre>
<p>We load the panel and hand it to <code>dataprep</code>, which returns the treated vector <code>y</code>, the <code>donor_matrix</code> of the 38 controls, and the number of pre-treatment periods.</p>
<div id="0c375c7b" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> mlsynth.utils.datautils <span class="im">import</span> dataprep</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>base_url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/jgreathouse9/mlsynth/refs/heads/main/"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> base_url <span class="op">+</span> <span class="st">"basedata/smoking_data.csv"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>prepped <span class="op">=</span> dataprep(</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    data,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    data.columns[<span class="dv">0</span>],   <span class="co"># unit   : state</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    data.columns[<span class="dv">1</span>],   <span class="co"># time   : year</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    data.columns[<span class="dv">2</span>],   <span class="co"># outcome: cigsale</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    data.columns[<span class="op">-</span><span class="dv">1</span>],  <span class="co"># treat  : Proposition 99</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now the estimator, exactly as the algebra prescribes. The uniform weights <span class="math inline">\(1/N_0\)</span> are applied by averaging the donor matrix across its columns; the intercept <span class="math inline">\(\beta^\ast\)</span> is the mean pre-treatment gap; the counterfactual is the shifted donor mean; and the ATT is the average post-treatment gap between California and that counterfactual.</p>
<div id="6a0d25df" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>y      <span class="op">=</span> prepped[<span class="st">"y"</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>T0     <span class="op">=</span> prepped[<span class="st">"pre_periods"</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>donors <span class="op">=</span> prepped[<span class="st">"donor_matrix"</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>N0     <span class="op">=</span> donors.shape[<span class="dv">1</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Uniform weights: every donor gets 1/N0. These are the SCM simplex weights,</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># planted at the centroid.</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> np.full(N0, <span class="fl">1.0</span> <span class="op">/</span> N0)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>donor_mean <span class="op">=</span> donors <span class="op">@</span> w                       <span class="co"># equivalently donors.mean(axis=1)</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># The one free parameter: the intercept beta*.</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>beta <span class="op">=</span> np.mean(y[:T0] <span class="op">-</span> donor_mean[:T0])</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>yhat <span class="op">=</span> donor_mean <span class="op">+</span> beta                       <span class="co"># the DID counterfactual</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>ATT  <span class="op">=</span> np.mean(y[T0:] <span class="op">-</span> yhat[T0:])</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"weights sum to      </span><span class="sc">{</span>w<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.4f}</span><span class="ss">, min weight </span><span class="sc">{</span>w<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.4f}</span><span class="ss">  (on the simplex)"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"intercept  beta*  =  </span><span class="sc">{</span>beta<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"ATT              =  </span><span class="sc">{</span>ATT<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>weights sum to      1.0000, min weight 0.0263  (on the simplex)
intercept  beta*  =  -14.3590
ATT              =  -27.3491</code></pre>
</div>
</div>
<p>The weights sum to one and are all positive, the intercept comes out to <span class="math inline">\(\beta^\ast \approx -14.36\)</span> — California smoked about 14 fewer packs per capita than the average control state before the law — and the ATT is about <span class="math inline">\(-27.35\)</span> packs per capita. Here is the picture.</p>
<div id="cell-fig-did-cali" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-did-cali" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-did-cali-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="didexcp_files/figure-html/fig-did-cali-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-did-cali-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Difference-in-Differences on Proposition 99: uniform donor weights plus an intercept.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The counterfactual does not hug California especially well before 1989 — it undershoots for the first few years and overshoots later. That misfit is the whole reason SCM exists, and it is parallel trends failing in front of you. The uniform weights force the counterfactual to be the <em>average</em> control state, shifted to California’s level; the intercept can only slide that line up and down, it cannot bend it. If California’s pre-period gap is not flat, no choice of <span class="math inline">\(\beta\)</span> will make it flat, and the gap you see before 1989 is a preview of the bias you cannot see after it.</p>
<p>None of this hangs on my hand-rolled arithmetic. The <a href="https://github.com/igerber/diff-diff"><code>diff-diff</code></a> package — a small, dedicated DID estimator, a cousin to my own <code>mlsynth</code> — computes the same effect from the plain <span class="math inline">\(2 \times 2\)</span> table, once we hand it the two indicators DID actually runs on: a treated-group flag (California, every year) and a post flag (every state, 1989 on).</p>
<div id="156bd56d" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> diff_diff <span class="im">import</span> DifferenceInDifferences</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># DID's two indicators, rebuilt from the panel: a treated-group flag</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># (California in every year) and a post flag (every state, 1989 on).</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>did_df <span class="op">=</span> data.copy()</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>treated_states <span class="op">=</span> data.loc[data[<span class="st">"Proposition 99"</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">"state"</span>].unique()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>post_years     <span class="op">=</span> data.loc[data[<span class="st">"Proposition 99"</span>] <span class="op">==</span> <span class="dv">1</span>, <span class="st">"year"</span>].unique()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>did_df[<span class="st">"treated"</span>] <span class="op">=</span> data[<span class="st">"state"</span>].isin(treated_states).astype(<span class="bu">int</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>did_df[<span class="st">"post"</span>]    <span class="op">=</span> data[<span class="st">"year"</span>].isin(post_years).astype(<span class="bu">int</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> DifferenceInDifferences().fit(</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    did_df, outcome<span class="op">=</span><span class="st">"cigsale"</span>, treatment<span class="op">=</span><span class="st">"treated"</span>, post<span class="op">=</span><span class="st">"post"</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DiDResults(ATT=-27.3491***, SE=4.5522, p=0.0000)</code></pre>
</div>
</div>
<p>Same ATT — about <span class="math inline">\(-27.35\)</span> — now carrying a standard error and a <span class="math inline">\(p\)</span>-value, from a routine that never heard of a weight vector or a simplex. It agrees because it is the same estimator under another name: the hand-rolled intercept <span class="math inline">\(\beta^\ast\)</span> is the average pre-period gap, and the <span class="math inline">\(2 \times 2\)</span> DID is that same gap differenced across the treatment date.</p>
</section>
<section id="so-what" class="level2">
<h2 class="anchored" data-anchor-id="so-what">So what?</h2>
<p>Now, you may be saying, “Hey Jared, this is a lot of algebra to conclude that a mean is a mean.” But the payoff is a clean way to see what you are actually assuming when you reach for DID, and why the choice between DID and SCM is a choice about weights and nothing else.</p>
<p>Both estimators answer the same question — what would California have done without Prop 99? — by averaging control states. DID commits to equal weights before it looks at the data; SCM lets the pre-treatment fit choose the weights. Neither fabricates a “fake” California or grafts together a “Frankenstein” unit, any more than the national average income fabricates a fake person. They both summarize real control units with weights that live on the same simplex. The difference is only whether those weights are handed to you as an axiom or estimated as a decision.</p>
<p>And the reason that decision matters shows up the moment you write untreated outcomes as a factor model, <span class="math inline">\(y_{jt}(0) = a_j + \mathbf{b}_j^\top \mathbf{f}_t + u_{jt}\)</span>. Averaging the donor pool averages its factor loadings <span class="math inline">\(\bar{\mathbf{b}}_0\)</span>, and — as I show in the book — the DID counterfactual is unbiased exactly when the treated unit’s loading equals that average, <span class="math inline">\(\mathbf{b}_1 = \bar{\mathbf{b}}_0\)</span>. That is parallel trends restated one more time: the leftover gap is <span class="math inline">\((\mathbf{b}_1 - \bar{\mathbf{b}}_0)^\top (\mathbf{f}_t - \bar{\mathbf{f}})\)</span>, a term that <em>moves with <span class="math inline">\(t\)</span></em> whenever the treated loading differs from the donor average — a gap no intercept can flatten. Uniform weights only reach California’s factor exposure if California happens to sit at the donor pool’s center of gravity. When it does not — and a state with California’s tobacco culture usually does not — you want the freedom to move the weights off the centroid, toward the donors that actually share its exposure. That freedom <em>is</em> synthetic control, and DID is the center of it you get by refusing to use it.</p>
<p>So the answer to the question I was asked is: DID is a synthetic control whose weight vector you filled in yourself, with <span class="math inline">\(1/N_0\)</span> in every slot, before the data had a chance to weigh in. Everything else — the loss, the simplex, the intercept, the counterfactual, and parallel trends itself — is shared. You are, as ever, never <em>not</em> averaging. The only question is who gets to pick the weights.</p>



</section>

<div class="quarto-listing quarto-listing-container-default" id="listing-listing">
<div class="list quarto-listing-default">
<div class="quarto-post image-right" data-index="0" data-listing-file-modified-sort="1789302328580" data-listing-reading-time-sort="1" data-listing-word-count-sort="16">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./index.html" class="no-external"></a>
</h3>
</div>
<div class="metadata">
<a href="./index.html" class="no-external">
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="1" data-listing-file-modified-sort="1789302257135" data-listing-reading-time-sort="1" data-listing-word-count-sort="22">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./testpost.html" class="no-external">A Test Post</a>
</h3>
</div>
<div class="metadata">
<a href="./testpost.html" class="no-external">
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="2" data-listing-file-modified-sort="1789302257128" data-listing-reading-time-sort="1" data-listing-word-count-sort="96">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./consulting.html" class="no-external">👋 Welcome</a>
</h3>
</div>
<div class="metadata">
<a href="./consulting.html" class="no-external">
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="3" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1786665600000" data-listing-file-modified-sort="1789302257132" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="27" data-listing-word-count-sort="5391">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./scdense2.html" class="no-external">Artificial Counterfactuals in Dense Settings: now with prediction intervals</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./scdense2.html" class="no-external">
<div class="listing-date">
Aug 14, 2026
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="4" data-categories="TWFjaGluZSUyMExlYXJuaW5nJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1770940800000" data-listing-file-modified-sort="1789302257135" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="15" data-listing-word-count-sort="2998">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./shaemax.html" class="no-external">Shake it to the Max? Using the <span class="math inline">\(\ell_\infty\)</span> norm for Synthetic Control Methods</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('TWFjaGluZSUyMExlYXJuaW5n'); return false;">Machine Learning</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./shaemax.html" class="no-external">
<div class="listing-date">
Feb 13, 2026
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="5" data-categories="RWNvbm9tZXRyaWMlMjBUaGVvcnklMkNTdGF0aXN0aWNz" data-listing-date-sort="1769644800000" data-listing-file-modified-sort="1789302257127" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="13" data-listing-word-count-sort="2516">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./averagesexcp.html" class="no-external">What Is An Average?</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWMlMjBUaGVvcnk='); return false;">Econometric Theory</div>

<div class="listing-category" onclick="window.quartoListingCategory('U3RhdGlzdGljcw=='); return false;">Statistics</div>

</div>
</div>
<div class="metadata">
<a href="./averagesexcp.html" class="no-external">
<div class="listing-date">
Jan 29, 2026
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="6" data-listing-date-sort="1758499200000" data-listing-file-modified-sort="1789302257135" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="29" data-listing-word-count-sort="5656">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./stella1.html" class="no-external">A Practitioner’s Guide to Weighted Synthetic Control Methods for Incrementality Testing</a>
</h3>
</div>
<div class="metadata">
<a href="./stella1.html" class="no-external">
<div class="listing-date">
Sep 22, 2025
</div>
</a><div class="listing-author"><a href="./stella1.html" class="no-external">
</a><a href="https://www.stellaheystella.com/blog/a-practitioners-guide-to-weighted-synthetic-control-methods-for-incrementality-testing">Stella Hey Stella</a>
</div>

</div>
</div>
<div class="quarto-post image-right" data-index="7" data-categories="RXhwZXJpbWVudHMlMkNFY29ub21ldHJpY3M=" data-listing-date-sort="1758326400000" data-listing-file-modified-sort="1789302257134" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="18" data-listing-word-count-sort="3587">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./scexp.html" class="no-external">Synthetic Controls for Marketing Experiments</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RXhwZXJpbWVudHM='); return false;">Experiments</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./scexp.html" class="no-external">
<div class="listing-date">
Sep 20, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="8" data-listing-date-sort="1757376000000" data-listing-file-modified-sort="1789302257132" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="29" data-listing-word-count-sort="5754">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./lfe1.html" class="no-external">Lessons from Econometrics, Part 1: Synthetic Controls Aren’t Black Boxes</a>
</h3>
</div>
<div class="metadata">
<a href="./lfe1.html" class="no-external">
<div class="listing-date">
Sep 9, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="9" data-categories="RWNvbm9tZXRyaWNzJTJDQ2F1c2FsJTIwSW5mZXJlbmNl" data-listing-date-sort="1754956800000" data-listing-file-modified-sort="1789302257135" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="14" data-listing-word-count-sort="2679">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./sparsdens.html" class="no-external">What is a Synthetic Control?</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

</div>
</div>
<div class="metadata">
<a href="./sparsdens.html" class="no-external">
<div class="listing-date">
Aug 12, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="10" data-categories="RWNvbm9tZXRyaWNz" data-listing-date-sort="1752710400000" data-listing-file-modified-sort="1789302257135" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="10" data-listing-word-count-sort="1836">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./shc.html" class="no-external">The Synthetic Historical Control Method</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./shc.html" class="no-external">
<div class="listing-date">
Jul 17, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="11" data-categories="RWNvbm9tZXRyaWNz" data-listing-date-sort="1752019200000" data-listing-file-modified-sort="1789302257135" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="6" data-listing-word-count-sort="1199">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./spillsynth.html" class="no-external">The Iterative Synthetic Control Method</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./spillsynth.html" class="no-external">
<div class="listing-date">
Jul 9, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="12" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1747612800000" data-listing-file-modified-sort="1789302257132" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="5" data-listing-word-count-sort="974">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./nsc.html" class="no-external">Synthetic Controls With Non-Linear Outcome Trends: A Principled Approach to Extrapolation</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./nsc.html" class="no-external">
<div class="listing-date">
May 19, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="13" data-categories="RWNvbm9tZXRyaWMlMjBUaGVvcnk=" data-listing-date-sort="1747008000000" data-listing-file-modified-sort="1789302257132" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1734">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./sccare.html" class="no-external">Synthetic Controls Do Not Care What Your Donors Are. So Why Do You?</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWMlMjBUaGVvcnk='); return false;">Econometric Theory</div>

</div>
</div>
<div class="metadata">
<a href="./sccare.html" class="no-external">
<div class="listing-date">
May 12, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="14" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1745884800000" data-listing-file-modified-sort="1789302257135" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="11" data-listing-word-count-sort="2178">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./synthinter.html" class="no-external">Synthetic Control Methods for Personalized Causal Inference</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./synthinter.html" class="no-external">
<div class="listing-date">
Apr 29, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="15" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1744761600000" data-listing-file-modified-sort="1789302257134" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="22" data-listing-word-count-sort="4204">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./scmo.html" class="no-external">Synthetic Controls With More Than One Outcome</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./scmo.html" class="no-external">
<div class="listing-date">
Apr 16, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="16" data-categories="TWFjaGluZSUyMExlYXJuaW5nJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1743552000000" data-listing-file-modified-sort="1789302257129" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1643">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./fscm.html" class="no-external">Forward Selected Synthetic Control</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('TWFjaGluZSUyMExlYXJuaW5n'); return false;">Machine Learning</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./fscm.html" class="no-external">
<div class="listing-date">
Apr 2, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="17" data-categories="R2l0aHViJTJDQXV0b21hdGlvbg==" data-listing-date-sort="1738281600000" data-listing-file-modified-sort="1789302257129" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1754">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./gitact.html" class="no-external">Data Science for Policy Analysts: A Simple Introduction to Github Actions</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('R2l0aHVi'); return false;">Github</div>

<div class="listing-category" onclick="window.quartoListingCategory('QXV0b21hdGlvbg=='); return false;">Automation</div>

</div>
</div>
<div class="metadata">
<a href="./gitact.html" class="no-external">
<div class="listing-date">
Jan 31, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="18" data-categories="V2ViJTIwU2NyYXBpbmclMkNQeXRob24=" data-listing-date-sort="1738108800000" data-listing-file-modified-sort="1789302257127" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="13" data-listing-word-count-sort="2403">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./aaascrape.html" class="no-external">Data Science for Policy Analysts: A Simple Introduction to Web Scraping</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('V2ViJTIwU2NyYXBpbmc='); return false;">Web Scraping</div>

<div class="listing-category" onclick="window.quartoListingCategory('UHl0aG9u'); return false;">Python</div>

</div>
</div>
<div class="metadata">
<a href="./aaascrape.html" class="no-external">
<div class="listing-date">
Jan 29, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="19" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1737676800000" data-listing-file-modified-sort="1789302257132" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="19" data-listing-word-count-sort="3704">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./scdense.html" class="no-external">Artificial Counterfactuals in Dense Settings: the <span class="math inline">\(\ell_2\)</span> relaxer</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./scdense.html" class="no-external">
<div class="listing-date">
Jan 24, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
</div>
<div class="listing-no-matching d-none">No matching items</div>
</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jgreathouse9\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Jared Greathouse</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script src="js/assumptions.js"></script>




</body></html>