<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.8">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jared Greathouse">
<meta name="dcterms.date" content="2025-08-17">

<title>Forward Selected Augmented Synthetic Controls – Policy Analysis, Data Science, and Causal Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-listing/list.min.js"></script>
<script src="site_libs/quarto-listing/quarto-listing.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-fae04a4dda57acfb7da1e58796bfa73f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b8ded578f01cf45f867b749dfb801973.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

  window.document.addEventListener("DOMContentLoaded", function (_event) {
    const listingTargetEl = window.document.querySelector('#listing-listing .list');
    if (!listingTargetEl) {
      // No listing discovered, do not attach.
      return; 
    }

    const options = {
      valueNames: ['listing-date','listing-title','listing-author','listing-categories',{ data: ['index'] },{ data: ['categories'] },{ data: ['listing-date-sort'] },{ data: ['listing-file-modified-sort'] }],
      
      searchColumns: ["listing-date","listing-title","listing-author","listing-image","listing-description","listing-categories"],
    };

    window['quarto-listings'] = window['quarto-listings'] || {};
    window['quarto-listings']['listing-listing'] = new List('listing-listing', options);

    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  });

  window.addEventListener('hashchange',() => {
    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  })
  </script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Policy Analysis, Data Science, and Causal Inference</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://jgreathouse9.github.io"> 
<span class="menu-text">About Jared</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#notations" id="toc-notations" class="nav-link" data-scroll-target="#notations">Notations</a></li>
  <li><a href="#synthetic-controls" id="toc-synthetic-controls" class="nav-link" data-scroll-target="#synthetic-controls">Synthetic Controls</a></li>
  <li><a href="#the-augmented-synthetic-control-estimator" id="toc-the-augmented-synthetic-control-estimator" class="nav-link" data-scroll-target="#the-augmented-synthetic-control-estimator">The Augmented Synthetic Control Estimator</a></li>
  </ul></li>
  <li><a href="#forward-selected-augmented-synthetic-controls" id="toc-forward-selected-augmented-synthetic-controls" class="nav-link" data-scroll-target="#forward-selected-augmented-synthetic-controls">Forward-Selected Augmented Synthetic Controls</a>
  <ul class="collapse">
  <li><a href="#conformal-prediction-intervals" id="toc-conformal-prediction-intervals" class="nav-link" data-scroll-target="#conformal-prediction-intervals">Conformal Prediction Intervals</a></li>
  </ul></li>
  <li><a href="#kansas-tax-cuts" id="toc-kansas-tax-cuts" class="nav-link" data-scroll-target="#kansas-tax-cuts">Kansas Tax Cuts</a></li>
  <li><a href="#proposition-99" id="toc-proposition-99" class="nav-link" data-scroll-target="#proposition-99">Proposition 99</a></li>
  </ul>
</nav>
    <h5 class="quarto-listing-category-title">Categories</h5><div class="quarto-listing-category category-default"><div class="category" data-category="">All <span class="quarto-category-count">(12)</span></div><div class="category" data-category="QXV0b21hdGlvbg==">Automation <span class="quarto-category-count">(1)</span></div><div class="category" data-category="Q2F1c2FsJTIwSW5mZXJlbmNl">Causal Inference <span class="quarto-category-count">(4)</span></div><div class="category" data-category="RWNvbm9tZXRyaWMlMjBUaGVvcnk=">Econometric Theory <span class="quarto-category-count">(1)</span></div><div class="category" data-category="RWNvbm9tZXRyaWNz">Econometrics <span class="quarto-category-count">(7)</span></div><div class="category" data-category="R2l0aHVi">Github <span class="quarto-category-count">(1)</span></div><div class="category" data-category="TWFjaGluZSUyMExlYXJuaW5n">Machine Learning <span class="quarto-category-count">(1)</span></div><div class="category" data-category="UHl0aG9u">Python <span class="quarto-category-count">(1)</span></div><div class="category" data-category="V2ViJTIwU2NyYXBpbmc=">Web Scraping <span class="quarto-category-count">(1)</span></div></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Forward Selected Augmented Synthetic Controls</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Causal Inference</div>
    <div class="quarto-category">Econometrics</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jared Greathouse </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 17, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p><a href="https://archive.is/20230120121731/https://www.washingtonpost.com/news/wonk/wp/2015/10/30/how-to-measure-things-in-a-world-of-competing-claims/">Synthetic Control Methods</a> (SCM) is a widely used framework for estimating causal effects when randomized experiments are not feasible. At its core, SCM constructs a weighted average of control (donor) units to approximate the treated unit’s pre-treatment trajectory. The goal is to find an in-sample/pre–treatment average of controls that closely mirrors the treated unit before the intervention.</p>
<p>Much of the method’s credibility hinges on the quality of this pre-treatment fit. Econometricians <a href="https://mixtape.scunning.com/10-synthetic_control">regularly</a> <a href="https://arxiv.org/pdf/2203.06279">warn</a> that poor pre-treatment fit undermines the validity of SCM estimates. Even if the optimization problem is formally well-posed, poor alignment between the treated unit and its in-sample match can lead to substantial bias. The intuition is straightforward: if similar units are <a href="https://doi.org/10.3982/ECTA21248">assumed to behave similarly</a>, a control group that fails to mimic the treated unit before treatment is unlikely to produce a credible counterfactual afterward. Just as important as pre-treatment fit is the composition of the donor pool. Including irrelevant or poorly matched units, or omitting relevant ones, can distort the synthetic weights and lead to misleading inferences. But how should the donor pool be chosen?</p>
<p>One increasingly popular solution to the imperfect match is the Augmented Synthetic Control Method (ASCM), known in industry through Meta’s <a href="https://facebookincubator.github.io/GeoLift/">GeoLift</a> library. Shops like <a href="https://geolift-docs.getrecast.com/docs/">Recast</a> use it, and data scientists such as <a href="https://medium.com/data-science/how-to-analyze-geo-based-campaigns-with-synthetic-control-a90b839479a8">Mandy Liu</a> and <a href="https://www.linkedin.com/posts/svet-semov-79072913_metas-geolift-activity-7341471937493200896-SFvd?utm_source=share&amp;utm_medium=member_desktop&amp;rcm=ACoAAB2Q8asBlsCYlwKJgJ488VWbcV1CX14FdOw">Svet Semov</a> have helped bring it to applied audiences.</p>
<p>Methods for donor pool selection have also received attention. In fact, this is part of what makes GeoLift so popular: it <a href="https://github.com/facebookincubator/GeoLift/blob/main/R/pre_test_power.R#L37">attempts to identify</a> the most similar markets to a treated group before the intervention. In academic settings, approaches like <a href="https://doi.org/10.1016/j.jeconom.2021.04.009">forward</a> <a href="https://pubsonline.informs.org/doi/10.1287/mksc.2022.0212">selection</a>, and even <a href="https://doi.org/10.1002/jae.3123">random forests</a> have been proposed to automate or guide the choice of appropriate donors.</p>
<p>But what if we can do better?</p>
<p>In previous posts, I’ve written about donor selection strategies and how to handle imperfect pre-treatment fit. In this post, I introduce a synthesis of both: the Augmented Forward-Selected Synthetic Control estimator. By combining forward selection with a bias correction estimator, I show that we can reduce in-sample risk relative to the standard ASCM and Forward SCM alone. This approach is illustrated using two popular SCM case studies: the Kansas tax cut experiment and California’s Proposition 99.</p>
<section id="notations" class="level3">
<h3 class="anchored" data-anchor-id="notations">Notations</h3>
<p>Formally, let <span class="math inline">\(\mathbb{R}\)</span> denote the set of real numbers. A calligraphic letter, such as <span class="math inline">\(\mathcal{S}\)</span>, represents a discrete set with cardinality <span class="math inline">\(S = |\mathcal{S}|\)</span>. Let <span class="math inline">\(j \in \mathbb{N}\)</span> index a total of <span class="math inline">\(N\)</span> units and <span class="math inline">\(t \in \mathbb{N}\)</span> index time. Unit <span class="math inline">\(j=1\)</span> is the treated unit, with the set of control units defined as <span class="math inline">\(\mathcal{N}_0 = \mathcal{N} \setminus \{1\}\)</span>, of cardinality <span class="math inline">\(N_0\)</span>. The pre-treatment period is <span class="math inline">\(\mathcal{T}_1 = \{ t \in \mathbb{N} : t \leq T_0 \}\)</span>, where <span class="math inline">\(T_0\)</span> is the last period before treatment, and the post-treatment period is <span class="math inline">\(\mathcal{T}_2 = \{ t \in \mathbb{N} : t &gt; T_0 \}\)</span>. The observed outcome for unit <span class="math inline">\(j\)</span> at time <span class="math inline">\(t\)</span> is <span class="math inline">\(y_{jt}\)</span>, and the generic outcome vector for unit <span class="math inline">\(j\)</span> is <span class="math inline">\(\mathbf{y}_j \in \mathbb{R}^T\)</span>, so that <span class="math inline">\(\mathbf{y}_j = (y_{j1}, y_{j2}, \dots, y_{jT})^\top\)</span>. The treated unit’s outcome vector is <span class="math inline">\(\mathbf{y}_1\)</span>, and the donor matrix is defined as <span class="math inline">\(\mathbf{Y}_0 \coloneqq \begin{bmatrix} \mathbf{y}_j \end{bmatrix}_{j \in \mathcal{N}_0} \in \mathbb{R}^{T \times N_0}\)</span>, with each column corresponding to a donor unit and each row corresponding to a time period.</p>
<p>I will frequently refer to linear combinations of the donor units’ outcomes. Two important geometric concepts help clarify the space of possible synthetic controls: The convex hull of the donor units, denoted <span class="math inline">\(\operatorname{conv}(\mathbf{y}_j)_{j \in \mathcal{N}_0}\)</span>, is the set of all weighted averages of donor vectors where the weights are non-negative and sum to one:</p>
<p><span class="math display">\[
\operatorname{conv}(\mathbf{y}_j) = \left\{ \sum_{j \in \mathcal{N}_0} w_j \mathbf{y}_j \,\middle|\, w_j \geq 0, \sum_{j} w_j = 1 \right\}.
\]</span> This is the feasible region for standard SCM weights <span class="math inline">\(\mathbf{w} \in \Delta^{N_0}\)</span>. The affine hull, denoted <span class="math inline">\(\operatorname{aff}(\mathbf{y}_j)_{j \in \mathcal{N}_0}\)</span>, is the set of all affine combinations of donor vectors — that is, the set of linear combinations where the weights sum to one, but may include negative values:</p>
<p><span class="math display">\[
  \operatorname{aff}(\mathbf{y}_j) = \left\{ \sum_{j \in \mathcal{N}_0} w_j \mathbf{y}_j \,\middle|\, \sum_{j} w_j = 1 \right\}.
\]</span> This is the feasible region for the ASC estimator. While both are weighted averages, the convex hull is a “weighted average” over the subsapce of the donor outcomes, while the affine hull is a “shifted subspace” that contains the convex hull but allows for extrapolation beyond it.</p>
<p>We define the corresponding sets of feasible weights as:</p>
<p><span class="math display">\[
\mathcal{W}_{\mathrm{conv}} = \left\{ \mathbf{w} \in \mathbb{R}^{N_0}_{\geq 0} \mid \; \|\mathbf{w}\|_1 = 1 \right\},
\]</span></p>
<p><span class="math display">\[
\mathcal{W}_{\mathrm{aff}} = \left\{ \mathbf{w} \in \mathbb{R}^{N_0} \mid \|\mathbf{w}\|_1 = 1 \right\},
\]</span></p>
<p>where <span class="math inline">\(\|\mathbf{w}\|_1 = \sum_{j=1}^{N_0} |w_j|\)</span> denotes the <span class="math inline">\(\ell_1\)</span> norm of the weight vector <span class="math inline">\(\mathbf{w}\)</span>, and <span class="math inline">\(\mathbf{1}\)</span> is the vector of ones in <span class="math inline">\(\mathbb{R}^{N_0}\)</span>. Note that for <span class="math inline">\(\mathcal{W}_{\mathrm{conv}}\)</span>, the weights are non-negative and sum to one (equivalently, their <span class="math inline">\(\ell_1\)</span> norm is one), whereas for <span class="math inline">\(\mathcal{W}_{\mathrm{aff}}\)</span> weights can be negative but must sum to one.</p>
<div id="17bfc4e4" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fasc_files/figure-html/cell-2-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="synthetic-controls" class="level2">
<h2 class="anchored" data-anchor-id="synthetic-controls">Synthetic Controls</h2>
<p>The classic SCM estimator solves the program</p>
<p><span class="math display">\[
\mathbf{w}^\ast = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{conv}}}{\operatorname*{argmin}} \; \left\| \mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w} \right\|_2^2 \quad \forall t \in \mathcal{T}_1.
\]</span></p>
<p>We seek the weight vector <span class="math inline">\(\mathbf{w} \in \mathcal{W}_{\mathrm{conv}}\)</span> that minimizes the mean squared error between the treated unit’s observed pre-treatment outcomes <span class="math inline">\(\mathbf{y}_1\)</span> and the weighted average of donor outcomes <span class="math inline">\(\mathbf{Y}_0 \mathbf{w}\)</span> over the pre-treatment period <span class="math inline">\(\mathcal{T}_1\)</span>. The forward selection variant constructs a sparse synthetic control by iteratively adding one donor unit at a time to minimize the pre-treatment fit error. Starting from the empty set <span class="math inline">\(\mathcal{S} = \emptyset\)</span> of selected donors, at each iteration, the algorithm examines each donor <span class="math inline">\(j \in \mathcal{N}_0 \setminus \mathcal{S}\)</span> and forms a candidate set <span class="math inline">\(\mathcal{S}^{\prime} = \mathcal{S} \cup \{j\}\)</span>. For each such candidate set <span class="math inline">\(\mathcal{S}^{\prime}\)</span>, it solves the restricted optimization problem over the donor submatrix <span class="math inline">\(\mathbf{Y}_0^{\mathcal{S}^{\prime}}\)</span>, defined as the columns of <span class="math inline">\(\mathbf{Y}_0\)</span> corresponding to units in <span class="math inline">\(\mathcal{S}^{\prime}\)</span>:</p>
<p><span class="math display">\[
\mathbf{w}_{\mathcal{S}^{\prime}}^{\ast} = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{conv}}(\mathcal{S}^{\prime})}{\operatorname*{argmin}} \; \left\| \mathbf{y}_1 - \mathbf{Y}_0^{\mathcal{S}^{\prime}} \mathbf{w} \right\|_2^2,
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\mathcal{W}_{\mathrm{conv}}(\mathcal{S}^{\prime}) = \left\{ \mathbf{w} \in \mathbb{R}_{\geq 0}^{|\mathcal{S}^{\prime}|} \,\middle|\, \sum_{j \in \mathcal{S}^{\prime}} w_j = 1 \right\}.
\]</span></p>
<p>The donor selected at each iteration is</p>
<p><span class="math display">\[
j^{\ast} = \underset{j \in \mathcal{N}_0 \setminus \mathcal{S}}{\operatorname*{argmin}} \; \min_{\mathbf{w} \in \mathcal{W}_{\mathrm{conv}}(\mathcal{S} \cup \{j\})} \left\| \mathbf{y}_1 - \mathbf{Y}_0^{\mathcal{S} \cup \{j\}} \mathbf{w} \right\|_2^2,
\]</span></p>
<p>and it is then added to the selected set by updating $ $. This process repeats until a stopping rule is met, such as a maximum number of donors or minimal improvement in fit. The donor selection process continues <a href="https://mlsynth.readthedocs.io/en/latest/fscm.html#fscm-function">at the discretion of the user</a>, until either all/some portion of donors have been exhausted, or a model selection criterion, the modified BIC, begins to increase and <code>full_selection = FALSE</code>. The modified BIC is defined as:</p>
<p><span class="math display">\[
\text{mBIC}(S) = T_0 \cdot \log(\text{MSE}) + |S| \cdot \log(T_0)
\]</span></p>
<p>where</p>
<p><span class="math display">\[
\text{MSE} = \frac{1}{T_0} \left\| \mathbf{y}_1 - \mathbf{Y}_0^S \mathbf{w}_S \right\|_2^2.
\]</span></p>
<p>This penalized error criterion trades off in-sample fit and model complexity, enabling the construction of a sparse but well-performing synthetic control using only a small, carefully chosen subset of donor units.</p>
</section>
<section id="the-augmented-synthetic-control-estimator" class="level2">
<h2 class="anchored" data-anchor-id="the-augmented-synthetic-control-estimator">The Augmented Synthetic Control Estimator</h2>
<p>Building on this baseline formulation, the ASCM introduces a regularization term that penalizes deviations of the weight vector from a reference or initial weight vector, <span class="math inline">\(\mathbf{w}_0\)</span>. The augmented objective can be written as</p>
<p><span class="math display">\[
\mathbf{w}^\ast_{\mathrm{aug}} = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{aff}}}{\operatorname*{argmin}} \; \left\| \mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w} \right\|_2^2 + \lambda \left\| \mathbf{w} - \mathbf{w}_0 \right\|_2^2 \quad \forall t \in \mathcal{T}_1.
\]</span></p>
<p>where <span class="math inline">\(\lambda \ge 0\)</span> controls the strength of the penalty.</p>
<details>
<summary>
About that lambda…
</summary>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>One may ask <em>“Jared, why did you include the penalty on the weight deviation term instead of the fit term, as Ben-Michael and co. do in Equation 18 of their paper?”</em> Here’s why.</p>
<p>In ASCM, the placement of the regularization parameter <span class="math inline">\(\lambda\)</span> determines how the estimator balances pre-treatment fit and fidelity to the original SCM weights. Their formulation (e.g., Ben-Michael et al.&nbsp;2021) minimizes:</p>
<p><span class="math display">\[
\mathbf{w}^\ast_{\text{alt}} = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{aff}}}{\operatorname*{argmin}} \; \lambda \|\mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w}\|_2^2 + \|\mathbf{w} - \mathbf{w}_0\|_2^2
\]</span></p>
<p>while ours solves:</p>
<p><span class="math display">\[
\mathbf{w}^\ast_{\text{aug}} = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{aff}}}{\operatorname*{argmin}} \; \|\mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w}\|_2^2 + \lambda \|\mathbf{w} - \mathbf{w}_0\|_2^2
\]</span></p>
<p>It turns out these are mathematically equivalent under a simple reparameterization. If we define <span class="math inline">\(\lambda_{\text{alt}} = \frac{1}{\lambda_{\text{aug}}}\)</span>, then both objectives yield the same solution. This follows directly from the first-order conditions of each problem, which differ only by a scaling of the Lagrange multiplier.</p>
<p>So in truth, it’s just a matter of which interpretation you find more natural.</p>
<p>I personally prefer our formulation. Here’s why: in the affine-regularized version of the forward-selected synthetic control, <span class="math inline">\(\mathbf{w}_0\)</span> comes from a deliberately chosen sparse model. As <span class="math inline">\(\lambda \to \infty\)</span>, the penalty on deviation dominates, and <span class="math inline">\(\mathbf{w}^\ast_{\text{aug}}\)</span> collapses to the projection of <span class="math inline">\(\mathbf{w}_0\)</span> onto the affine constraint <span class="math inline">\(\sum_j w_j = 1\)</span>. This makes intuitive sense: when the original FSCM fit is already good, we want to stick close to it.</p>
<p>Conversely, as <span class="math inline">\(\lambda \to 0\)</span>, the regularization term disappears and the solution becomes the best-fitting affine combination of the donor units — completely unconstrained by the initial weights. That’s appropriate when the original fit is poor and we’re willing to learn something new.</p>
<p>So while the math is equivalent, the perspective isn’t. I find it more natural to think of <span class="math inline">\(\lambda\)</span> as controlling how much I “trust” the prior weights. And that’s easier to reason about when <span class="math inline">\(\lambda\)</span> is attached to the deviation term.</p>
</div>
</div>
</details>
<p>The intuition here is pretty simple. If the SCM weights are already giving us good pre-treatment fit, then there is little incentive to extrapolate away from the original (F)SCM solution. However, if there’s need for better fit, then we will extrapolate away from the convex hull solution. In practice, BMFR advocate for choosing lambda via cross validation.</p>
</section>
</section>
<section id="forward-selected-augmented-synthetic-controls" class="level1">
<h1>Forward-Selected Augmented Synthetic Controls</h1>
<p>The Forward-Selected Augmented Synthetic Control (FASC) estimator synthesizes two complementary strategies in SCM research: forward selection of donors and bias correction via the discrepancy correction, <span class="math inline">\(\left\| \mathbf{w} - \mathbf{w}_0 \right\|_2^2\)</span>. It begins with a Forward SCM as described above, selecting a small set of donors that best approximate the treated unit in the pre-treatment period via forward selection. Let the weight vector for this solution be <span class="math inline">\(\mathbf{w}_0\)</span>. Then, it augments this base model with a bias-corrected adjustment by seeing whether an affine combination can do better than the convex combination, using the original weights as a warm start. The FASC solves:</p>
<p><span class="math display">\[
\mathbf{w}^\ast_{\text{FASC}} = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{aff}}}{\operatorname*{argmin}} \; \left\| \mathbf{y}_1 - \mathbf{Y}_0 \mathbf{w} \right\|_2^2 + \lambda \left\| \mathbf{w} - \mathbf{w}_0 \right\|_2^2.
\]</span></p>
<p>The solution lies in the affine hull of all donors, but it is regularized to remain close to the sparse, interpretable model obtained from forward selection on the condition that the originally selected model is good. The strength of this regularization is governed by the parameter <span class="math inline">\(\lambda\)</span>. The regularization parameter <span class="math inline">\(\lambda\)</span> is selected via time-split cross-validation on the pre-treatment period. First, use the first half (<span class="math inline">\(t = 1, \dots, \lfloor T_0/2 \rfloor\)</span>) to fit candidate weights <span class="math inline">\(\mathbf{w}(\lambda)\)</span>. Then, use the second half (<span class="math inline">\(t = \lfloor T_0/2 \rfloor + 1, \dots, T_0\)</span>) to evaluate prediction error. For each candidate <span class="math inline">\(\lambda\)</span>, we compute:</p>
<p><span class="math display">\[
\mathbf{w}(\lambda) = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{aff}}}{\operatorname*{argmin}} \left\| \mathbf{y}^{(1)} - \mathbf{Y}_0^{(1)} \mathbf{w} \right\|_2^2 + \lambda \left\| \mathbf{w} - \mathbf{w}_0 \right\|_2^2.
\]</span> The expression <span class="math inline">\(\text{CV-RMSE}(\lambda)\)</span> measures the out-of-sample prediction error on the second half of the pre-treatment period when using weights <span class="math inline">\(\mathbf{w}(\lambda)\)</span> fitted on the first half. Specifically, it calculates the Euclidean norm (root sum of squared differences) between the observed outcomes <span class="math inline">\(\mathbf{y}^{(2)}\)</span> of the treated unit and the synthetic control’s predicted outcomes <span class="math inline">\(\mathbf{Y}_0^{(2)} \mathbf{w}(\lambda)\)</span>. Minimizing this cross-validated root mean squared error helps select the regularization parameter <span class="math inline">\(\lambda\)</span> that balances fit and regularization to improve generalization to unseen (post-first-half) data. <span class="math display">\[
\text{CV-RMSE}(\lambda) = \left\| \mathbf{y}^{(2)} - \mathbf{Y}_0^{(2)} \mathbf{w}(\lambda) \right\|_2.
\]</span></p>
<p>To efficiently explore the hyperparameter space, I use <code>skopt</code>’s Bayesian optimization over <span class="math inline">\(\log_{10}(\lambda) \in [-2, 3]\)</span>, corresponding to <span class="math inline">\(\lambda \in [10^{-2}, 10^3]\)</span>. The optimization proceeds as follows: A Gaussian Process (GP) prior is placed over the unknown function <span class="math inline">\(\lambda \mapsto \text{CV-RMSE}(\lambda)\)</span>. This GP models both the mean and uncertainty of the objective function. The algorithm begins with a small number of initial random evaluations. At each step, the next <span class="math inline">\(\lambda\)</span> to evaluate is chosen by maximizing an acquisition function, in this case the Expected Improvement (EI), which balances exploration and exploitation. This process continues for a total of 50 steps (or as specified). Once the optimal <span class="math inline">\(\lambda^\ast\)</span> is identified, the final weight vector is estimated by solving:</p>
<p><span class="math display">\[
\mathbf{w}^{\ast} = \underset{\mathbf{w} \in \mathcal{W}_{\mathrm{aff}}}{\operatorname*{argmin}} \left\| \mathbf{y} - \mathbf{Y}_0 \mathbf{w} \right\|_2^2 + \lambda^{\ast} \left\| \mathbf{w} - \mathbf{w}_0 \right\|_2^2.
\]</span></p>
<p>The resulting weights lie in the affine hull of the donor pool and strike a balance between fitting the treated unit and remaining close to the original sparse solution. As above, when <span class="math inline">\(\lambda\)</span> is large, the augmented weights remain close to <span class="math inline">\(\mathbf{w}_0\)</span>; when <span class="math inline">\(\lambda\)</span> is small, the estimator prioritizes fit over sparsity and may extrapolate well beyond the original donor set. In essence, FS-ASC gives us the best of both worlds: interpretability and parsimony from sparse donor selection, and flexibility and reduced bias from affine augmentation. Empirically (we will see this below), it yields lower pre-treatment error than either method alone.</p>
<div id="9d5df5ef" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fasc_files/figure-html/cell-3-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="conformal-prediction-intervals" class="level2">
<h2 class="anchored" data-anchor-id="conformal-prediction-intervals">Conformal Prediction Intervals</h2>
<p>To quantify uncertainty around the estimated counterfactual trajectory, we apply <a href="https://matheusfacure.github.io/python-causality-handbook/Conformal-Inference-for-Synthetic-Control.html">conformal prediction intervals</a> based on block-permuted pre-treatment residuals. These intervals are distribution-free, require no assumptions about the data-generating process, and provide valid finite-sample marginal coverage. Let <span class="math inline">\(\hat{y}_t^{\text{cf}}\)</span> denote the estimated counterfactual outcome at time <span class="math inline">\(t\)</span>, and let <span class="math inline">\(y_t^{\text{obs}}\)</span> be the observed outcome. We begin by computing residuals for all time periods:</p>
<p><span class="math display">\[
\varepsilon_t = y_t^{\text{obs}} - \hat{y}_t^{\text{cf}}.
\]</span></p>
<p>We then construct a conformal score by calculating the mean absolute residual over the post-treatment period. To simulate the distribution of this score under the null (i.e., assuming no treatment effect), we perform circular block permutations of the residual vector and recompute the same statistic for each shifted version.</p>
<p>This yields an empirical distribution of conformal scores under the null. We take the <span class="math inline">\((1 - \alpha)\)</span> quantile of this distribution as our conformal threshold, denoted <span class="math inline">\(q_{1 - \alpha}\)</span>. To center the interval, we compute the mean residual over the pre-treatment period:</p>
<p><span class="math display">\[
\bar{\varepsilon} = \frac{1}{T_0} \sum_{t \leq T_0} \varepsilon_t.
\]</span></p>
<p>The conformal prediction interval for each post-treatment time <span class="math inline">\(t &gt; T_0\)</span> is then given by:</p>
<p><span class="math display">\[
\left[ \hat{y}_t^{\text{cf}} + \bar{\varepsilon} - q_{1 - \alpha},\ \hat{y}_t^{\text{cf}} + \bar{\varepsilon} + q_{1 - \alpha} \right].
\]</span></p>
<p>This approach ensures that the prediction intervals account for uncertainty in the counterfactual trajectory while adjusting for systematic bias in the pre-treatment fit. The shaded regions in our figures visualize these conformal intervals.</p>
</section>
</section>
<section id="kansas-tax-cuts" class="level1">
<h1>Kansas Tax Cuts</h1>
<p>Here are the results of the FASC method.</p>
<div id="ffe6a2a0" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stderr">
<pre><code>/opt/hostedtoolcache/Python/3.13.6/x64/lib/python3.13/site-packages/mlsynth/utils/datautils.py:434: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  observations_per_unit = df.groupby(unit_id_column_name)[time_period_column_name].nunique() # Changed from .count() to .nunique() for robustness</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="fasc_files/figure-html/cell-4-output-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>I compare the pretreatment and posttreatment fit of Forward SCM (FSCM) and its Augmented variant (ASCM). Both estimators were applied to the same treated unit over a common pre- and post-treatment period.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th>Estimator</th>
<th>Pre-RMSE</th>
<th>Post-RMSE</th>
<th>R²</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forward SCM</td>
<td>0.012</td>
<td>0.014</td>
<td>0.999</td>
<td>Baseline sparse estimator</td>
</tr>
<tr class="even">
<td>Augmented SCM</td>
<td>0.012</td>
<td>0.014</td>
<td>0.999</td>
<td>Ridge-augmented refinement</td>
</tr>
<tr class="odd">
<td>Ben Michael (SCM)</td>
<td>0.90</td>
<td>–</td>
<td>–</td>
<td>Some imbalance</td>
</tr>
<tr class="even">
<td>Ben Michael (ASCM)</td>
<td>0.65</td>
<td>–</td>
<td>–</td>
<td>RMSE reduced by ~28% from SCM</td>
</tr>
</tbody>
</table>
<p>Both FSCM and its ridge-augmented variant achieve nearly identical performance, with a pre-RMSE of 0.012 and an out-of-sample RMSE of 0.014. Since the donor selection is already good, the addition of regularization does not improve predictive accuracy, indicating that the original FSCM fit is already near-optimal. In contrast, the original SCM fit exhibits a much larger pre-RMSE of 0.90. While ASCM reduces this error to 0.65, the improvement is modest by comparison to FASC. Relative to these benchmarks, FASC approach achieves a <em>98.7% reduction in pre-RMSE</em> compared to standard SCM, and a <em>98.2% reduction</em> compared to augmented SCM with ridge. Of course, these were just the default settings; for higher dimensional donor pools, we could use stopping rules to make the selection process quicker. Also notice that inference has not yet been programmed just yet.</p>
</section>
<section id="proposition-99" class="level1">
<h1>Proposition 99</h1>
<p>I compare the effect of Proposition 99 on cigarette sales in California using FASC, FSCM, and the original SCM. While all three detect a significant reduction in sales, the quality of pretreatment fit varies meaningfully.</p>
<div id="1c5b3e24" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd <span class="co"># To work with panel data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> mlsynth <span class="im">import</span> FSCM</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/jgreathouse9/mlsynth/refs/heads/main/basedata/smoking_data.csv"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.read_csv(url)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>config <span class="op">=</span> {</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"df"</span>: data,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"outcome"</span>: data.columns[<span class="dv">2</span>],</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"treat"</span>: data.columns[<span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"unitid"</span>: data.columns[<span class="dv">0</span>],</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"time"</span>: data.columns[<span class="dv">1</span>],</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"display_graphs"</span>: <span class="va">True</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"save"</span>: <span class="va">False</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"counterfactual_color"</span>: [<span class="st">"blue"</span>, <span class="st">"#00F0FF"</span>], <span class="st">"use_augmented"</span>: <span class="va">True</span>}</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>arco <span class="op">=</span> FSCM(config).fit()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="fasc_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Estimator</th>
<th>ATT</th>
<th>Pre-RMSE</th>
<th><span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>FASC</td>
<td>-16.76</td>
<td><strong>0.935</strong></td>
<td><strong>0.993</strong></td>
</tr>
<tr class="even">
<td>FSCM</td>
<td>-19.51</td>
<td>1.656</td>
<td>0.979</td>
</tr>
<tr class="odd">
<td>ADH (Stata)</td>
<td>-19.00</td>
<td>1.76</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>FASC achieves the best pretreatment fit, with a root mean squared error of 0.935 and an <span class="math inline">\(R^2\)</span> of 0.993. This represents a <strong>46% reduction in pre-RMSE compared to FSCM</strong> and a <strong>47% reduction relative to the original ADH implementation</strong>. The improved fit comes with a slightly smaller estimated ATT (-16.76) compared to FSCM (-19.51) and ADH (-19.00), suggesting that regularized, forward-selected models may, if slightly, temper exaggerated effects while maintaining excellent in-sample risk.</p>
<p>FASC produces weights that differ notably from both FSCM and the original SCM with covariates. While the vanilla FSCM weights are sparse and non-negative, concentrated on a small set of donors such as Utah, Montana, Nevada, and Connecticut, the augmented FSCM weights are less sparse and include small negative values, as we would expect. These negative weights allow the augmented estimator to extrapolate slightly beyond the convex hull formed by the donors, thus providing controlled flexibility to improve the pre-treatment fit. Importantly, the augmented weights <em>still maintain the core donor pool</em> emphasized by the vanilla FSCM, with similar magnitudes on key states — for example, Utah (~0.38), Montana (~0.24), Nevada (~0.21), and Connecticut (~0.14). The original SCM with covariates also concentrates weight on a similar subset of donors, including Utah, Nevada, Montana, Colorado, and Connecticut, demonstrating stability in donor selection across methods.</p>
<p>The presence of small negative weights in the augmented FSCM, assigned to peripheral donors such as Alabama, Mississippi, and Tennessee, acts as fine-tuning adjustments to better capture the treated unit’s trajectory. Machine learning scientsts <a href="https://jmlr.csail.mit.edu/papers/volume19/17-777/17-777.pdf">have remarked</a> that there’s not obvious reason why the donor weights need to bo convex; Ben-Michael, Feller, and Rothstein argue that such extrapolation, provided that it is controlled, is worth it in settings where the base estimator produces poor in-sample risk. Overall, these patterns underscore how augmentation refines the synthetic control weights, offering a nuanced improvement over vanilla forward selection by reducing bias without sacrificing the stability or interpretability of the donor composition.</p>



</section>

<div class="quarto-listing quarto-listing-container-default" id="listing-listing">
<div class="list quarto-listing-default">
<div class="quarto-post image-right" data-index="0" data-categories="V2ViJTIwU2NyYXBpbmclMkNQeXRob24=" data-listing-date-sort="1738108800000" data-listing-file-modified-sort="1755464205207" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="13" data-listing-word-count-sort="2403">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./aaascrape.html" class="no-external">Data Science for Policy Analysts: A Simple Introduction to Web Scraping</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('V2ViJTIwU2NyYXBpbmc='); return false;">Web Scraping</div>

<div class="listing-category" onclick="window.quartoListingCategory('UHl0aG9u'); return false;">Python</div>

</div>
</div>
<div class="metadata">
<a href="./aaascrape.html" class="no-external">
<div class="listing-date">
Jan 29, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="1" data-categories="R2l0aHViJTJDQXV0b21hdGlvbg==" data-listing-date-sort="1738281600000" data-listing-file-modified-sort="1755464205208" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1754">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./gitact.html" class="no-external">Data Science for Policy Analysts: A Simple Introduction to Github Actions</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('R2l0aHVi'); return false;">Github</div>

<div class="listing-category" onclick="window.quartoListingCategory('QXV0b21hdGlvbg=='); return false;">Automation</div>

</div>
</div>
<div class="metadata">
<a href="./gitact.html" class="no-external">
<div class="listing-date">
Jan 31, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="2" data-categories="TWFjaGluZSUyMExlYXJuaW5nJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1743552000000" data-listing-file-modified-sort="1755464205208" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1643">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./fscm.html" class="no-external">Forward Selected Synthetic Control</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('TWFjaGluZSUyMExlYXJuaW5n'); return false;">Machine Learning</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./fscm.html" class="no-external">
<div class="listing-date">
Apr 2, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="3" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1744761600000" data-listing-file-modified-sort="1755464205213" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="22" data-listing-word-count-sort="4204">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./scmo.html" class="no-external">Synthetic Controls With More Than One Outcome</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./scmo.html" class="no-external">
<div class="listing-date">
Apr 16, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="4" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1745884800000" data-listing-file-modified-sort="1755464205213" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="11" data-listing-word-count-sort="2178">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./synthinter.html" class="no-external">Synthetic Control Methods for Personalized Causal Inference</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./synthinter.html" class="no-external">
<div class="listing-date">
Apr 29, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="5" data-categories="RWNvbm9tZXRyaWMlMjBUaGVvcnk=" data-listing-date-sort="1747008000000" data-listing-file-modified-sort="1755464205210" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1734">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./sccare.html" class="no-external">Synthetic Controls Do Not Care What Your Donors Are. So Why Do You?</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWMlMjBUaGVvcnk='); return false;">Econometric Theory</div>

</div>
</div>
<div class="metadata">
<a href="./sccare.html" class="no-external">
<div class="listing-date">
May 12, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="6" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1747612800000" data-listing-file-modified-sort="1755464205210" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="5" data-listing-word-count-sort="974">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./nsc.html" class="no-external">Synthetic Controls With Non-Linear Outcome Trends: A Principled Approach to Extrapolation</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./nsc.html" class="no-external">
<div class="listing-date">
May 19, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="7" data-categories="RWNvbm9tZXRyaWNz" data-listing-date-sort="1752019200000" data-listing-file-modified-sort="1755464205213" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="6" data-listing-word-count-sort="1159">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./spillsynth.html" class="no-external">The Iterative Synthetic Control Method</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./spillsynth.html" class="no-external">
<div class="listing-date">
Jul 9, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="8" data-categories="RWNvbm9tZXRyaWNz" data-listing-date-sort="1752710400000" data-listing-file-modified-sort="1755464205213" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="10" data-listing-word-count-sort="1836">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./shc.html" class="no-external">The Synthetic Historical Control Method</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./shc.html" class="no-external">
<div class="listing-date">
Jul 17, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="9" data-categories="RWNvbm9tZXRyaWNzJTJDQ2F1c2FsJTIwSW5mZXJlbmNl" data-listing-date-sort="1754956800000" data-listing-file-modified-sort="1755464205213" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="14" data-listing-word-count-sort="2679">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./sparsdens.html" class="no-external">What is a Synthetic Control?</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

</div>
</div>
<div class="metadata">
<a href="./sparsdens.html" class="no-external">
<div class="listing-date">
Aug 12, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="10" data-listing-file-modified-sort="1755464264913" data-listing-reading-time-sort="1" data-listing-word-count-sort="17">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./index.html" class="no-external">Policy Analysis, Data Science, and Causal Inference</a>
</h3>
</div>
<div class="metadata">
<a href="./index.html" class="no-external">
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="11" data-listing-file-modified-sort="1755464205208" data-listing-reading-time-sort="1" data-listing-word-count-sort="98">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./consulting.html" class="no-external">👋 Welcome</a>
</h3>
</div>
<div class="metadata">
<a href="./consulting.html" class="no-external">
</a>
</div>
</div>
</div>
<div class="listing-no-matching d-none">No matching items</div>
</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jgreathouse9\.github\.io\/docs\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Jared Greathouse</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>