<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.8">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jared Greathouse">
<meta name="dcterms.date" content="2025-09-20">

<title>Synthetic Controls for Marketing Experiments – Policy Analysis, Data Science, and Causal Inference</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-listing/list.min.js"></script>
<script src="site_libs/quarto-listing/quarto-listing.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-fae04a4dda57acfb7da1e58796bfa73f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7a7c4e549630ecf835dfbe41ebefbb26.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>

  window.document.addEventListener("DOMContentLoaded", function (_event) {
    const listingTargetEl = window.document.querySelector('#listing-listing .list');
    if (!listingTargetEl) {
      // No listing discovered, do not attach.
      return; 
    }

    const options = {
      valueNames: ['listing-date','listing-title','listing-author','listing-categories',{ data: ['index'] },{ data: ['categories'] },{ data: ['listing-date-sort'] },{ data: ['listing-file-modified-sort'] }],
      
      searchColumns: ["listing-date","listing-title","listing-author","listing-subtitle","listing-image","listing-description","listing-categories"],
    };

    window['quarto-listings'] = window['quarto-listings'] || {};
    window['quarto-listings']['listing-listing'] = new List('listing-listing', options);

    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  });

  window.addEventListener('hashchange',() => {
    if (window['quarto-listing-loaded']) {
      window['quarto-listing-loaded']();
    }
  })
  </script>
<script>
window.MathJax = {
  tex: {
    macros: {
      defeq: "\\mathrel{\\mathop:}=",
      // Add more macros below as needed
      // R: "\\mathbb{R}",
      // E: "\\mathbb{E}",
      // Var: "\\operatorname{Var}"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Policy Analysis, Data Science, and Causal Inference</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://jgreathouse9.github.io"> 
<span class="menu-text">About Jared</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-difficulties-of-market-experimentation" id="toc-the-difficulties-of-market-experimentation" class="nav-link active" data-scroll-target="#the-difficulties-of-market-experimentation">The Difficulties of Market Experimentation</a></li>
  <li><a href="#notation-and-econometric-methodology" id="toc-notation-and-econometric-methodology" class="nav-link" data-scroll-target="#notation-and-econometric-methodology">Notation and Econometric Methodology</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#the-optimization" id="toc-the-optimization" class="nav-link" data-scroll-target="#the-optimization">The Optimization</a></li>
  <li><a href="#design-variations" id="toc-design-variations" class="nav-link" data-scroll-target="#design-variations">Design Variations</a></li>
  <li><a href="#inference" id="toc-inference" class="nav-link" data-scroll-target="#inference">Inference</a></li>
  <li><a href="#intuition" id="toc-intuition" class="nav-link" data-scroll-target="#intuition">Intuition</a></li>
  </ul></li>
  <li><a href="#a-simulated-example" id="toc-a-simulated-example" class="nav-link" data-scroll-target="#a-simulated-example">A Simulated Example</a>
  <ul class="collapse">
  <li><a href="#non-willemstad" id="toc-non-willemstad" class="nav-link" data-scroll-target="#non-willemstad">Non-Willemstad</a></li>
  <li><a href="#willemstad" id="toc-willemstad" class="nav-link" data-scroll-target="#willemstad">Willemstad</a></li>
  <li><a href="#one-cluster-setup-all-units" id="toc-one-cluster-setup-all-units" class="nav-link" data-scroll-target="#one-cluster-setup-all-units">One-Cluster Setup: All Units</a></li>
  </ul></li>
  <li><a href="#takeaways-for-practice" id="toc-takeaways-for-practice" class="nav-link" data-scroll-target="#takeaways-for-practice">Takeaways for Practice</a></li>
  </ul>
</nav>
    <h5 class="quarto-listing-category-title">Categories</h5><div class="quarto-listing-category category-default"><div class="category" data-category="">All <span class="quarto-category-count">(18)</span></div><div class="category" data-category="QXV0b21hdGlvbg==">Automation <span class="quarto-category-count">(1)</span></div><div class="category" data-category="Q2F1c2FsJTIwSW5mZXJlbmNl">Causal Inference <span class="quarto-category-count">(5)</span></div><div class="category" data-category="RWNvbm9tZXRyaWMlMjBUaGVvcnk=">Econometric Theory <span class="quarto-category-count">(2)</span></div><div class="category" data-category="RWNvbm9tZXRyaWNz">Econometrics <span class="quarto-category-count">(9)</span></div><div class="category" data-category="R2l0aHVi">Github <span class="quarto-category-count">(1)</span></div><div class="category" data-category="TWFjaGluZSUyMExlYXJuaW5n">Machine Learning <span class="quarto-category-count">(2)</span></div><div class="category" data-category="UHl0aG9u">Python <span class="quarto-category-count">(1)</span></div><div class="category" data-category="U3RhdGlzdGljcw==">Statistics <span class="quarto-category-count">(1)</span></div><div class="category" data-category="V2ViJTIwU2NyYXBpbmc=">Web Scraping <span class="quarto-category-count">(1)</span></div></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Synthetic Controls for Marketing Experiments</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Experiments</div>
    <div class="quarto-category">Econometrics</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jared Greathouse </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 20, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-difficulties-of-market-experimentation" class="level1">
<h1>The Difficulties of Market Experimentation</h1>
<p><a href="https://www.travelpulse.com/news/destinations/curacao-takes-proactive-steps-toward-sustainability-amid-global-overtourism">Suppose the government of Curaçao</a> wants to implement a new <a href="https://www.businesstravelnewseurope.com/Accommodation/HRS-Green-Stay-updates-are-set-to-increase-hotel-participation">“Green Stay” initiative</a> that encourages hotels to adopt sustainability measures, such as reducing water usage, improving waste management, and shifting toward renewable energy. Such initiatives are becoming <a href="https://www.travelandtourworld.com/news/article/aruba-manchebo-beach-resort-and-spa-reinforces-sustainable-practices-now-with-green-globe-platinum-recertification/">increasingly</a> <a href="https://www.travelagewest.com/Travel/Caribbean/eco-hotels-caribbean">popular</a> in recent years. But evaluating whether these policies actually work presents a fundamental challenge for market researchers.</p>
<p>From a methodological standpoint, the ideal approach would be a randomized controlled trial (RCT), in which some hotels implement the policy while others serve as controls. Randomization ensures that treated and control groups are balanced <em>in expectation</em>, so that any differences in outcomes after implementation can be attributed to the policy. RCTs provide a clear framework for statistical inference and are widely regarded as the gold standard for impact evaluation.</p>
<p>In practice, however, conducting an RCT in this context is fraught with challenges. Ethically, randomly granting some hotels the benefits of the program while denying them to others may be perceived as unfair, particularly if the policy enhances reputation, attracts eco-conscious travelers, or provides financial advantages. Politically, coordinating randomization across hundreds of hotels would require buy-in from government agencies, hotel associations, and local businesses, some of whom may resist being “experimented on.” Tourism being central to the island’s economy, any perception of risk could provoke public concern. Logistically, enforcing varying sustainability requirements across many independent hotels would be complex and costly, making large-scale randomization impractical.</p>
<p>A more feasible alternative is to focus on the market at a cluster level, grouping neighborhoods that share similar characteristics, such as geographic location, customer demographics, or historical tourist activity. Clustering mitigates ethical concerns, because selection occurs within naturally similar groups rather than arbitrarily across the entire market. It also reduces logistical complexity: interventions can be coordinated at the cluster level, and within each cluster, neighborhoods chosen as treated or control reflect the cluster’s underlying dynamics rather than idiosyncratic behavior.</p>
<p>The question then becomes: how do we select which neighborhoods to treat and which to use as controls? We could throw darts at a map to decide, but this is unlikely to produce reliable estimates. Instead, the goal should be to select both a treated group of units and a control group of units which look like the cluster/group level aggregate. <a href="https://arxiv.org/abs/2108.02196">Synthetic control methods</a> offer a solution, constructing “synthetic treated units” and “synthetic control units” that closely mimic the characteristics of clusters, enabling rigorous estimation of treatment effects even when randomization is infeasible.</p>
</section>
<section id="notation-and-econometric-methodology" class="level1">
<h1>Notation and Econometric Methodology</h1>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<p>As usual, this is where we get into the math details. In our Curaçao Green Stay example, the unit of treatment is the neighborhood, not individual hotels. That is, entire neighborhoods may adopt sustainability measures, while others remain untreated.</p>
<p>Let <span class="math display">\[
\mathcal{J} = \{1, \dots, J\}
\]</span> denote the set of neighborhoods, nested within clusters <span class="math display">\[
\mathcal{K} = \{1, \dots, K\},
\]</span> which group neighborhoods with similar characteristics (e.g., location, tourist demographics, historical occupancy). For each cluster <span class="math inline">\(k \in \mathcal{K}\)</span>, let <span class="math display">\[
I_k \subseteq \mathcal{J}
\]</span> denote its member neighborhoods. Each neighborhood <span class="math inline">\(j \in \mathcal{J}\)</span> belongs to exactly one cluster, denoted <span class="math inline">\(k(j)\)</span>, so that <span class="math inline">\(j \in I_{k(j)}\)</span>.</p>
<p>Time is divided into pre-treatment, blank, fitting, and post-treatment periods. Formally, we define</p>
<p><span class="math display">\[
\mathcal{T}_0 = \{1, \dots, T_0\}, \quad
\mathcal{T}_1 = \{1, \dots, T_0 - |\mathcal{B}|\}, \quad
\mathcal{B} = \{T_0 - |\mathcal{B}| + 1, \dots, T_0\}, \quad
\mathcal{T}_2 = \{T_0 + 1, \dots, T\}.
\]</span></p>
<p>Here <span class="math inline">\(\mathcal{T}_0\)</span> is the full pre-treatment period (128 observations in our example), <span class="math inline">\(\mathcal{T}_1\)</span> is the fitting period used to compute synthetic control weights and assignments, <span class="math inline">\(\mathcal{B}\)</span> is a blank period withheld for placebo checks (28 observations), and <span class="math inline">\(\mathcal{T}_2\)</span> is the post-treatment period.</p>
<p>Observed outcomes, such as occupancy rates or energy use, are collected in the outcome matrix</p>
<p><span class="math display">\[
\mathbf{Y} \in \mathbb{R}^{J \times T},
\]</span></p>
<p>where <span class="math inline">\(y_{jt}\)</span> represents the outcome for neighborhood <span class="math inline">\(j \in \mathcal{J}\)</span> at time <span class="math inline">\(t \in \mathcal{T}_0 \cup \mathcal{T}_2\)</span>. Potential outcomes are written as <span class="math inline">\(y_{jt}^I\)</span> if neighborhood <span class="math inline">\(j\)</span> participates in Green Stay and <span class="math inline">\(y_{jt}^N\)</span> if not, where <span class="math inline">\(I\)</span> denotes treated and <span class="math inline">\(N\)</span> denotes untreated.</p>
<p>The cluster-weighted average treatment effect at time <span class="math inline">\(t &gt; T_0\)</span> is</p>
<p><span class="math display">\[
\tau_t = \sum_{j=1}^J f_j \,(y_{jt}^I - y_{jt}^N),
\]</span></p>
<p>where <span class="math inline">\(f_j \ge 0\)</span> and <span class="math inline">\(\sum_{j=1}^J f_j = 1\)</span>. These weights may represent, for example, the relative population or importance of neighborhoods.</p>
<p>Pre-treatment characteristics of neighborhoods are captured in predictor vectors <span class="math display">\[
\mathbf{x}_j \in \mathbb{R}^r,
\]</span> such as average energy use, hotel occupancy, or guest demographics. Cluster means are defined using the same weights <span class="math inline">\(f_j\)</span> as</p>
<p><span class="math display">\[
\bar{\mathbf{x}}_k = \frac{\sum_{j \in I_k} f_j \, \mathbf{x}_j}{\sum_{j \in I_k} f_j}.
\]</span></p>
<p>Synthetic treated and control neighborhoods are defined via weights <span class="math inline">\(w_j \ge 0\)</span> and <span class="math inline">\(v_j \ge 0\)</span> respectively, with neighborhood-level treatment assignments <span class="math inline">\(z_j \in \{0,1\}\)</span>. The clustered synthetic control estimator is obtained by solving</p>
<p><span class="math display">\[
\min_{(\mathbf{w},\mathbf{v}) \in \mathcal{F}} \; \mathcal{L}(\mathbf{w},\mathbf{v}),
\]</span></p>
<p>where <span class="math inline">\(\mathcal{F}\)</span> is the feasible set defined by nonnegativity, within–cluster normalization, exclusivity, and any budget constraints. Each cluster <span class="math inline">\(k \in \mathcal{K}\)</span> has member indices <span class="math inline">\(I_k\)</span>, cluster mean <span class="math inline">\(\bar{\mathbf{x}}_k\)</span>, and outcomes <span class="math inline">\(\mathbf{X}_{I_k}\)</span>.</p>
</section>
<section id="the-optimization" class="level2">
<h2 class="anchored" data-anchor-id="the-optimization">The Optimization</h2>
<p>The optimization problem chooses synthetic treated and control neighborhoods by minimizing a loss function subject to feasibility constraints. At its core, the method constructs weighted averages of units to be treated and untreated, such that both averages resemble the cluster as a whole and each other. In addition to the above, we also may face operational costs <span class="math inline">\(\mathbf{c}\)</span> and cluster budgets <span class="math inline">\(B_k\)</span> which constrain feasible assignments. Explicitly, the feasible set is</p>
<p><span class="math display">\[
\begin{aligned}
\mathcal{F} = \Big\{ (w,v) \,\Big| \;
&amp; w_j, v_j \ge 0, \quad \sum_{j \in I_k} w_j = \sum_{j \in I_k} v_j = 1, \\
&amp; z_j \in \{0,1\}, \quad w_j \le z_j, \quad v_j \le 1 - z_j, \\
&amp; \sum_{j \in I_k} z_j \in [m_{\text{min},k}, m_{\text{max},k}], \\
&amp; \sum_{j \in I_k} c_j w_j \le B_k, \quad \sum_{k=1}^K \sum_{j \in I_k} c_j w_j \le B_{\text{total}}
\Big\}.
\end{aligned}
\]</span></p>
<p>Non-negativity (<span class="math inline">\(w_j, v_j \ge 0\)</span>) and normalization (<span class="math inline">\(\sum_{j \in I_k} w_j = \sum_{j \in I_k} v_j = 1\)</span>) ensure synthetic neighborhoods are convex combinations of real neighborhoods. The decision variable <span class="math inline">\(z_j \in \{0,1\}\)</span>, together with <span class="math inline">\(w_j \le z_j\)</span> and <span class="math inline">\(v_j \le 1 - z_j\)</span>, enforces exclusivity: each neighborhood contributes to either the synthetic treated unit or the synthetic control unit, but not both. Cardinality constraints (<span class="math inline">\(\sum_{j \in I_k} z_j \in [m_{\text{min},k}, m_{\text{max},k}]\)</span>) ensure that at least one neighborhood is treated in each cluster. Budget constraints (<span class="math inline">\(\sum c_j w_j \le B_k\)</span>, <span class="math inline">\(\sum c_j w_j \le B_{\text{total}}\)</span>) incorporate heterogeneous treatment costs across neighborhoods.</p>
</section>
<section id="design-variations" class="level2">
<h2 class="anchored" data-anchor-id="design-variations">Design Variations</h2>
<p>Abadie and Zhou propose several ways of implementing the synthetic control design. The base experimental SC estimator is the most straightforward. For each cluster <span class="math inline">\(k\)</span>, it tries to make the synthetic treated and synthetic control neighborhoods look like the cluster mean:</p>
<p><span class="math display">\[
\mathcal{L}_{\text{Base}}(\mathbf{w},\mathbf{v}) = \sum_{k=1}^K \big( \mathbf{f}_{I_k}^\top \mathbf{1} \big) \Big[
\|\bar{\mathbf{x}}_k - \mathbf{X}_{I_k}^\top \mathbf{w}_{I_k}\|_2^2
+ \|\bar{\mathbf{x}}_k - \mathbf{X}_{I_k}^\top \mathbf{v}_{I_k}\|_2^2
\Big].
\]</span></p>
<p>This design anchors both sides of the experiment to the same benchmark, namely the cluster mean.</p>
<p>The weakly targeted estimator extends this idea by also encouraging the treated and control groups to resemble each other directly:</p>
<p><span class="math display">\[
\mathcal{L}_{\text{Weak}}(\mathbf{w},\mathbf{v}) = \mathcal{L}_{\text{Base}}(\mathbf{w},\mathbf{v})
+ \beta \|\mathbf{X}_{I_k}^\top \mathbf{w}_{I_k} - \mathbf{X}_{I_k}^\top \mathbf{v}_{I_k}\|_2^2.
\]</span></p>
<p>In practice, this prevents the optimization from drifting toward two synthetic groups that both match the cluster mean but diverge from each other. Here as <span class="math inline">\(\beta\)</span> increases, we tend to the ATT instead of the ATE.</p>
<p>The penalized estimator incorporates distance-based penalties that favor neighborhoods closer to the cluster mean:</p>
<p><span class="math display">\[
\begin{aligned}
\mathcal{L}_{\text{Penalized}}(\mathbf{w}, \mathbf{v})
&amp;= \sum_{k=1}^K \Bigg[
\underbrace{\|\bar{\mathbf{x}}_k - \mathbf{X}_{I_k}^\top \mathbf{w}_{I_k}\|_2^2}_{\text{fit treated to cluster mean}}
+ \underbrace{\|\bar{\mathbf{x}}_k - \mathbf{X}_{I_k}^\top \mathbf{v}_{I_k}\|_2^2}_{\text{fit control to cluster mean}} \\
&amp;\quad + \lambda_1 \underbrace{\sum_{j \in I_k} w_j \|\mathbf{X}_j - \bar{\mathbf{x}}_k\|_2^2}_{\text{treated distance penalty}}
+ \lambda_2 \underbrace{\sum_{j \in I_k} v_j \|\mathbf{X}_j - \bar{\mathbf{x}}_k\|_2^2}_{\text{control distance penalty}}
\Bigg].
\end{aligned}
\]</span></p>
<p>This penalizes weights placed on neighborhoods far from the cluster mean, enforcing a kind of sparsity.</p>
<p>Finally, the unit-level estimator introduces the most granular design. It not only enforces closeness to cluster means but also requires that each treated neighborhood, individually, has a close match with its synthetic control:</p>
<p><span class="math display">\[
\begin{aligned}
\mathcal{L}_{\text{Unit}}(\mathbf{w}, \mathbf{v})
&amp;= \sum_{k=1}^K \Bigg[
\underbrace{\|\bar{\mathbf{x}}_k - \mathbf{X}_{I_k}^\top \mathbf{w}_{I_k}\|_2^2}_{\text{treated fit to cluster mean}}
+ \underbrace{\|\bar{\mathbf{x}}_k - \mathbf{X}_{I_k}^\top \mathbf{v}_{I_k}\|_2^2}_{\text{control fit to cluster mean}} \\
&amp;\quad + \underbrace{\xi \sum_{j \in I_k} w_j \|\mathbf{X}_j - \mathbf{X}_{I_k}^\top \mathbf{v}_{I_k}\|_2^2}_{\text{unit-level treated-control match}} \\
&amp;\quad + \underbrace{\lambda_{1,\text{unit}} \sum_{j \in I_k} w_j \|\mathbf{X}_j - \bar{\mathbf{x}}_k\|_2^2}_{\text{treated distance to cluster mean}}
+ \underbrace{\lambda_{2,\text{unit}} \sum_{j \in I_k} v_j \|\mathbf{X}_j - \mathbf{X}_{I_k}^\top \mathbf{w}_{I_k}\|_2^2}_{\text{control distance to treated synthetic}}
\Bigg].
\end{aligned}
\]</span></p>
<p>Analysts can select whichever design best aligns with the goals and constraints of their study.</p>
</section>
<section id="inference" class="level2">
<h2 class="anchored" data-anchor-id="inference">Inference</h2>
<p>The next step is to estimate the treatment effects and quantify uncertainty. For each neighborhood <span class="math inline">\(j\)</span> in cluster <span class="math inline">\(k\)</span>, the synthetic treated and control outcomes at time <span class="math inline">\(t \in \mathcal{T}_2\)</span> are constructed as weighted averages of the units. The difference between these outcomes is the unit-level treatment effect: <span class="math inline">\(\hat{\tau}_{j \in \mathcal{N}_1 t} = w_{j}y_{j \in \mathcal{N}_1 t} - v_{j}y_{j \in \mathcal{N}_0 t}\)</span>. Within each cluster, unit-level effects are aggregated using pre-specified weights <span class="math inline">\(f_j\)</span> to obtain the cluster-level effect: <span class="math inline">\(\hat{\tau}_{k t} = \sum_{j \in I_k, z_j = 1} f_j \hat{\tau}_{j \in \mathcal{N}_1 t}\)</span>. Summing over clusters gives the overall treatment effect: <span class="math inline">\(\hat{\tau}_t = \sum_{k=1}^K \hat{\tau}_{k t} = \sum_{j \in \mathcal{J}, z_j = 1} f_j \hat{\tau}_{j \in \mathcal{N}_1 t}\)</span>.</p>
<p>To build confidence intervals, we use the distribution of in-time placebo effects. These are computed in the blank pre-treatment period <span class="math inline">\(\mathcal{B}\)</span> and capture residual fluctuations when no treatment is applied. The cluster-level placebo effect is <span class="math inline">\(\hat{\tau}_{k t}^{\mathcal{B}} = \sum_{j \in I_k, z_j = 1} f_j (w_j y_{jt} - v_j y_{jt}), \quad t \in \mathcal{B}\)</span>. Global placebo effects are obtained by summing across clusters:</p>
<p><span class="math inline">\(\hat{\tau}_t^{\mathcal{B}} = \sum_{k=1}^K \hat{\tau}_{k t}^{\mathcal{B}}, \quad t \in \mathcal{B}\)</span>. Split-conformal confidence intervals are then constructed. For the global effect, we take the <span class="math inline">\((1-\alpha)\)</span> quantile of the absolute placebo effects: <span class="math inline">\(q_{1-\alpha} = \text{Quantile}_{1-\alpha}(|\hat{\tau}_t^{\mathcal{B}}|), \quad t \in \mathcal{B}\)</span>, and define the confidence interval as <span class="math inline">\(\mathrm{CI}_t = [\hat{\tau}_t - q_{1-\alpha}, \hat{\tau}_t + q_{1-\alpha}], \quad t \in \mathcal{T}_2\)</span>. Cluster-level confidence intervals are defined similarly, replacing global effects with the corresponding cluster-level placebo distributions.</p>
<p>Statistical significance can be assessed using permutation tests. The observed global statistic is <span class="math inline">\(S_{\text{obs}} = \frac{1}{|\mathcal{T}_2|} \sum_{t \in \mathcal{T}_2} |\hat{\tau}_t|\)</span>. By randomly sampling permutations from placebo and post-treatment effects, we generate test statistics <span class="math inline">\(S_{\text{perm}}^{(b)} = \frac{1}{|\mathcal{T}_2|} \sum_{t \in \text{sample}} |\hat{\tau}_t|, \quad b = 1, \dots, B\)</span>, and compute the global p-value as <span class="math inline">\(p_{\text{global}} = \frac{1}{B} \sum_{b=1}^B \mathbf{1}\{S_{\text{perm}}^{(b)} \ge S_{\text{obs}}\}\)</span>. Cluster-level significance tests follow the same logic using the cluster-level placebo distributions.</p>
</section>
<section id="intuition" class="level2">
<h2 class="anchored" data-anchor-id="intuition">Intuition</h2>
<p>Let’s take a step back from all the matrices, weights, and constraints and ask: what does this framework actually <em>do</em> in practice? All the math above essentially boils down to this: we are choosing who gets treated and who serves as control by building weighted averages of neighborhoods, under a set of explicit rules.</p>
<p>Think of the experimental synthetic control framework not as a mysterious math exercise, but as a decision-making engine for planning market experiments before we do any effect size estimation. After all, suppose you or I were literally hired by the government to do this. Their goal is to figure out which neighborhoods (or groups of units) should receive a treatment—say, implementing sustainability initiatives—and which should serve as controls. These choices should not (and realistically, cannot) be made arbitrarily. They must follow rules set by the client, which encode trade-offs among fairness, cost, representativeness, and logistical feasibility.</p>
<p>The first step is grouping neighborhoods into clusters that share characteristics such as geographic proximity, tourist demographics, historical activity, or energy usage. This makes the comparisons meaningful: apples to apples, not apples to pineapples. In this setting, our goal is inference about the <em>average treatment effect</em>, not just the effect on the treated. That distinction matters: we care about market-level representativeness, not only the treated group itself.</p>
<p>From here, analysts specify objectives. Should treated neighborhoods closely resemble the average of their cluster? Or should the match be tighter at the unit level? Different design variations encode different answers. Meanwhile, real-world constraints—budgets, minimum or maximum treated units per cluster, operational limitations, ethical concerns—are encoded directly in the optimization.</p>
<p>The optimization then selects synthetic treated and control neighborhoods. Instead of picking actual neighborhoods at random or by instinct, the framework identifies weighted combinations of neighborhoods that best satisfy the objectives and constraints. The base estimator makes both sides look like the cluster mean. The weakly targeted estimator (recall the <span class="math inline">\(\beta\)</span> penalty) pushes treated and control groups to resemble each other directly. Penalized and unit-level estimators add distance-based terms, reflecting geography, demographics, or other practical considerations we might want to code in.</p>
<p>What comes out of the optimization is a <em>recommendation</em>: given the priorities and constraints, here is the set of neighborhoods to treat, and here is the synthetic control to compare against. Policymakers can then implement the plan—working with hotel associations, local communities, or other stakeholders—knowing fairness and feasibility were accounted for upfront. Later, when post-treatment data arrive, analysts reuse the same synthetic control weights for causal estimation. The design stage and the inference stage are tied together by the same set of weights.</p>
<p>In this sense, experimental SC is a full-cycle experimental design tool. It is not only about estimating effects—it is about making a plan for who gets treated and why. Analysts can tune parameters to explore trade-offs: for example, increasing <span class="math inline">\(\beta\)</span> prioritizes representativeness of treated neighborhoods relative to controls. This flexibility turns the framework into a sandbox for scenario planning: simulate different designs, see how assignments shift, and produce recommendations that are realistic and robust.</p>
<p>That’s the bridge from theory to practice. The real question is: <em>given our goals, constraints, and the characteristics of this market, which neighborhoods should we treat, and why?</em></p>
</section>
</section>
<section id="a-simulated-example" class="level1">
<h1>A Simulated Example</h1>
<p>I applied the experimental synthetic control method to the Curaçao Green Stay example, estimating treatment effects by constructing synthetic treated and control units with simulated data. The analysis uses the Mixed Integer Quadratic Programming formulation of the objective. I selected 1 to 3 treated units per cluster, with pre-treatment fit assessed via root mean squared error (RMSE). Below, I summarize results for two clustering setups (two clusters and one cluster) and different penalty settings.</p>
<section id="non-willemstad" class="level2">
<h2 class="anchored" data-anchor-id="non-willemstad">Non-Willemstad</h2>
<p>The pre-treatment RMSE for Cluster 0 (Non-Willemstad) is 0.215, indicating an excellent pre-treatment fit. The synthetic control is constructed from the following control units:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Unit</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Barber</td>
<td>0.124</td>
</tr>
<tr class="even">
<td>Lagún</td>
<td>0.062</td>
</tr>
<tr class="odd">
<td>Santa Rosa</td>
<td>0.281</td>
</tr>
<tr class="even">
<td>Westpunt</td>
<td>0.533</td>
</tr>
</tbody>
</table>
<p>The treated group is represented by the following units:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Unit</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sint Willibrordus</td>
<td>0.382</td>
</tr>
<tr class="even">
<td>Soto</td>
<td>0.303</td>
</tr>
<tr class="odd">
<td>Spaanse Water</td>
<td>0.315</td>
</tr>
</tbody>
</table>
<p>Here, Westpunt dominates the control group at 53.3% and Sint Willibrordus leads the treated group at 38.2%. With balanced weights and an excellent fit, this setup indicates reliable treatment effect estimates for non-Willemstad areas.</p>
</section>
<section id="willemstad" class="level2">
<h2 class="anchored" data-anchor-id="willemstad">Willemstad</h2>
<p>The pre-treatment RMSE for Cluster 1 (Willemstad) is 0.413, representing a fine fit though less precise than in Cluster 0. The synthetic control draws from these control units:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Unit</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Groot Kwartier</td>
<td>0.093</td>
</tr>
<tr class="even">
<td>Groot Piscadera</td>
<td>0.302</td>
</tr>
<tr class="odd">
<td>Piscadera Bay</td>
<td>0.605</td>
</tr>
</tbody>
</table>
<p>The treated group consists of the following units:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Unit</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Otrobanda</td>
<td>0.415</td>
</tr>
<tr class="even">
<td>Saliña</td>
<td>0.306</td>
</tr>
<tr class="odd">
<td>Scharloo</td>
<td>0.279</td>
</tr>
</tbody>
</table>
<p>Here for the controls, Piscadera Bay exerts heavy influence on the synthetic control at 60.5% and Otrobanda heads the treated group at 41.5%. The somewhat higher RMSE implies slightly less confidence in treatment effect estimates for Willemstad, but the overall fit remains acceptable.</p>
<div id="fbb2e3c0" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stderr">
<pre><code>/opt/hostedtoolcache/Python/3.13.11/x64/lib/python3.13/site-packages/mlsynth/config_models.py:61: UserWarning:

DataFrame was not sorted by [town, time] — auto-sorting applied.
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="scexp_files/figure-html/cell-2-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="one-cluster-setup-all-units" class="level2">
<h2 class="anchored" data-anchor-id="one-cluster-setup-all-units">One-Cluster Setup: All Units</h2>
<p>When treating all units as a single cluster, the pre-treatment RMSE is 0.449, which, given outcome values in the 40s, represents a very small error and a reasonable fit for analysis. The control group is formed from the following units:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Unit</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Barber</td>
<td>0.137</td>
</tr>
<tr class="even">
<td>Santa Rosa</td>
<td>0.029</td>
</tr>
<tr class="odd">
<td>Scharloo</td>
<td>0.728</td>
</tr>
<tr class="even">
<td>Soto</td>
<td>0.107</td>
</tr>
</tbody>
</table>
<p>The treated group consists of these units:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Unit</th>
<th>Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pietermaai</td>
<td>0.239</td>
</tr>
<tr class="even">
<td>Piscadera Bay</td>
<td>0.537</td>
</tr>
<tr class="odd">
<td>Tera Corá</td>
<td>0.224</td>
</tr>
</tbody>
</table>
<div id="f42f3798" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stderr">
<pre><code>/opt/hostedtoolcache/Python/3.13.11/x64/lib/python3.13/site-packages/mlsynth/config_models.py:61: UserWarning:

DataFrame was not sorted by [town, time] — auto-sorting applied.
</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="scexp_files/figure-html/cell-3-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This RMSE of 0.449 indicates a fine fit, with Scharloo heavily influencing the control group at 72.8% and Piscadera Bay dominating the treated group at 53.7%. The fit, while slightly less precise than Cluster 0’s RMSE of 0.215, remains robust given the scale of the outcomes and supports reliable treatment effect estimates. The results show that the penalized design obtains good pretreatment fit <span class="math inline">\(\lambda_1 = \lambda_2 = 0.02\)</span> penalties. Of course, in reality we can choose these lambdas via cross validation, instead of setting them manually. These were just chosen for the sake of example. Either way, the synthetic design is robust whether we divide Curaçao into clusters or treat it as a single unit. Also, these data were simualted <a href="https://en.wikipedia.org/wiki/List_of_populated_places_in_Cura%C3%A7ao">from Wikipedia</a>, in theory <a href="https://www.citypopulation.de/en/curacao/admin/">we could get both population and density data</a> on a wider variety of places in Curaçao, with a more sophisitcated hierarchical linear factor model, to see how the estimator would play with even more clusters/units.</p>
</section>
</section>
<section id="takeaways-for-practice" class="level1">
<h1>Takeaways for Practice</h1>
<p>Notice that I have not yet discussed the ATT/ATE or the uncertainty of estimated treatment effects. That Is because the framework above is focused on <strong>experimental design</strong>. The main goal is to decide <em>who should be treated and why</em> before any real-world intervention. In other words, we can be confident in the design itself—who is treated, who is not, and why—before estimating treatment effects or reporting uncertainty. In the above example, the data were simulated under no treatment effect, to illustrate how the design works independently of any effect size. If a treatment were applied, we could then evaluate its impact using the design we have already validated. Crucially, in settings with few treatable units, synthetic control designs can achieve balance similar to an RCT, even when only a handful of units are treated. In fact, Abadie and Zhou show that “synthetic control design can substantially outperform randomized designs in experimental settings with a small number of treated units.” This allows interventions to be targeted strategically, saving resources while maintaining a valid identification strategy.</p>
<p>Contrast this with a traditional RCT. In an RCT, randomization occurs once in the field. Designing an RCT is costly and requires coordination across multiple actors. We cannot experiment with different randomization schemes beforehand, because the quality of the randomization can only be assessed <em>after</em> it occurs. Once units are assigned, the study must proceed, with all associated costs, risks, and constraints. By contrast, the synthetic control design can be iterated rapidly on a laptop. We can explore different cluster groupings, penalties, cost and budget constraints, or solver formulations, and observe how stable the resulting design is before committing any resources. This flexibility makes synthetic experimentation a powerful planning tool. It enables researchers and practitioners to prototype experiments cheaply and safely, such that the treated and control group to be a balanced as possible before any real-world action. Abadie and Zhou, and myslef, still see large-scale RCTs as the gold standard: they will not go away just because SCM can be a companion to them. However given their substantial costs and logistically demanding, synthetic experimentation open the door to an iterative, exploratory phase of experimental planning, especially when only a few units may be treated. That way, when we do invest in a full study, it is built on a solid foundation that is aware of operational, budgetary, and practical constraints.</p>



</section>

<div class="quarto-listing quarto-listing-container-default" id="listing-listing">
<div class="list quarto-listing-default">
<div class="quarto-post image-right" data-index="0" data-listing-file-modified-sort="1767703589952" data-listing-reading-time-sort="1" data-listing-word-count-sort="96">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./consulting.html" class="no-external">👋 Welcome</a>
</h3>
</div>
<div class="metadata">
<a href="./consulting.html" class="no-external">
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="1" data-listing-file-modified-sort="1767703658591" data-listing-reading-time-sort="1" data-listing-word-count-sort="16">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./index.html" class="no-external"></a>
</h3>
</div>
<div class="metadata">
<a href="./index.html" class="no-external">
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="2" data-listing-file-modified-sort="1767703589959" data-listing-reading-time-sort="1" data-listing-word-count-sort="22">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./testpost.html" class="no-external">A Test Post</a>
</h3>
</div>
<div class="metadata">
<a href="./testpost.html" class="no-external">
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="3" data-categories="TWFjaGluZSUyMExlYXJuaW5nJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1767484800000" data-listing-file-modified-sort="1767703589958" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="16" data-listing-word-count-sort="3189">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./shaemax.html" class="no-external">Shake it to the Max? Using the <span class="math inline">\(\ell_\infty\)</span> norm for Synthetic Control Methods</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('TWFjaGluZSUyMExlYXJuaW5n'); return false;">Machine Learning</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./shaemax.html" class="no-external">
<div class="listing-date">
Jan 4, 2026
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="4" data-categories="RWNvbm9tZXRyaWMlMjBUaGVvcnklMkNTdGF0aXN0aWNz" data-listing-date-sort="1767484800000" data-listing-file-modified-sort="1767703589952" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1690">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./averagesexcp.html" class="no-external">You Are Taking An Average</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWMlMjBUaGVvcnk='); return false;">Econometric Theory</div>

<div class="listing-category" onclick="window.quartoListingCategory('U3RhdGlzdGljcw=='); return false;">Statistics</div>

</div>
</div>
<div class="metadata">
<a href="./averagesexcp.html" class="no-external">
<div class="listing-date">
Jan 4, 2026
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="5" data-listing-date-sort="1758499200000" data-listing-file-modified-sort="1767703589959" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="29" data-listing-word-count-sort="5656">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./stella1.html" class="no-external">A Practitioner’s Guide to Weighted Synthetic Control Methods for Incrementality Testing</a>
</h3>
</div>
<div class="metadata">
<a href="./stella1.html" class="no-external">
<div class="listing-date">
Sep 22, 2025
</div>
</a><div class="listing-author"><a href="./stella1.html" class="no-external">
</a><a href="https://www.stellaheystella.com/blog/a-practitioners-guide-to-weighted-synthetic-control-methods-for-incrementality-testing">Stella Hey Stella</a>
</div>

</div>
</div>
<div class="quarto-post image-right" data-index="6" data-listing-date-sort="1757376000000" data-listing-file-modified-sort="1767703589955" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="29" data-listing-word-count-sort="5754">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./lfe1.html" class="no-external">Lessons from Econometrics, Part 1: Synthetic Controls Aren’t Black Boxes</a>
</h3>
</div>
<div class="metadata">
<a href="./lfe1.html" class="no-external">
<div class="listing-date">
Sep 9, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="7" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1755388800000" data-listing-file-modified-sort="1767703589952" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="21" data-listing-word-count-sort="4193">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./fasc.html" class="no-external">Forward Augmented Synthetic Controls</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./fasc.html" class="no-external">
<div class="listing-date">
Aug 17, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="8" data-categories="RWNvbm9tZXRyaWNzJTJDQ2F1c2FsJTIwSW5mZXJlbmNl" data-listing-date-sort="1754956800000" data-listing-file-modified-sort="1767703589958" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="14" data-listing-word-count-sort="2679">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./sparsdens.html" class="no-external">What is a Synthetic Control?</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

</div>
</div>
<div class="metadata">
<a href="./sparsdens.html" class="no-external">
<div class="listing-date">
Aug 12, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="9" data-categories="RWNvbm9tZXRyaWNz" data-listing-date-sort="1752710400000" data-listing-file-modified-sort="1767703589958" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="10" data-listing-word-count-sort="1836">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./shc.html" class="no-external">The Synthetic Historical Control Method</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./shc.html" class="no-external">
<div class="listing-date">
Jul 17, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="10" data-categories="RWNvbm9tZXRyaWNz" data-listing-date-sort="1752019200000" data-listing-file-modified-sort="1767703589959" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="6" data-listing-word-count-sort="1159">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./spillsynth.html" class="no-external">The Iterative Synthetic Control Method</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./spillsynth.html" class="no-external">
<div class="listing-date">
Jul 9, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="11" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1747612800000" data-listing-file-modified-sort="1767703589955" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="5" data-listing-word-count-sort="974">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./nsc.html" class="no-external">Synthetic Controls With Non-Linear Outcome Trends: A Principled Approach to Extrapolation</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./nsc.html" class="no-external">
<div class="listing-date">
May 19, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="12" data-categories="RWNvbm9tZXRyaWMlMjBUaGVvcnk=" data-listing-date-sort="1747008000000" data-listing-file-modified-sort="1767703589955" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1734">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./sccare.html" class="no-external">Synthetic Controls Do Not Care What Your Donors Are. So Why Do You?</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWMlMjBUaGVvcnk='); return false;">Econometric Theory</div>

</div>
</div>
<div class="metadata">
<a href="./sccare.html" class="no-external">
<div class="listing-date">
May 12, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="13" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1745884800000" data-listing-file-modified-sort="1767703589959" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="11" data-listing-word-count-sort="2178">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./synthinter.html" class="no-external">Synthetic Control Methods for Personalized Causal Inference</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./synthinter.html" class="no-external">
<div class="listing-date">
Apr 29, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="14" data-categories="Q2F1c2FsJTIwSW5mZXJlbmNlJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1744761600000" data-listing-file-modified-sort="1767703589958" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="22" data-listing-word-count-sort="4204">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./scmo.html" class="no-external">Synthetic Controls With More Than One Outcome</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('Q2F1c2FsJTIwSW5mZXJlbmNl'); return false;">Causal Inference</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./scmo.html" class="no-external">
<div class="listing-date">
Apr 16, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="15" data-categories="TWFjaGluZSUyMExlYXJuaW5nJTJDRWNvbm9tZXRyaWNz" data-listing-date-sort="1743552000000" data-listing-file-modified-sort="1767703589953" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1643">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./fscm.html" class="no-external">Forward Selected Synthetic Control</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('TWFjaGluZSUyMExlYXJuaW5n'); return false;">Machine Learning</div>

<div class="listing-category" onclick="window.quartoListingCategory('RWNvbm9tZXRyaWNz'); return false;">Econometrics</div>

</div>
</div>
<div class="metadata">
<a href="./fscm.html" class="no-external">
<div class="listing-date">
Apr 2, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="16" data-categories="R2l0aHViJTJDQXV0b21hdGlvbg==" data-listing-date-sort="1738281600000" data-listing-file-modified-sort="1767703589953" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="9" data-listing-word-count-sort="1754">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./gitact.html" class="no-external">Data Science for Policy Analysts: A Simple Introduction to Github Actions</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('R2l0aHVi'); return false;">Github</div>

<div class="listing-category" onclick="window.quartoListingCategory('QXV0b21hdGlvbg=='); return false;">Automation</div>

</div>
</div>
<div class="metadata">
<a href="./gitact.html" class="no-external">
<div class="listing-date">
Jan 31, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
<div class="quarto-post image-right" data-index="17" data-categories="V2ViJTIwU2NyYXBpbmclMkNQeXRob24=" data-listing-date-sort="1738108800000" data-listing-file-modified-sort="1767703589951" data-listing-date-modified-sort="NaN" data-listing-reading-time-sort="13" data-listing-word-count-sort="2403">
<div class="body">
<h3 class="no-anchor listing-title">
<a href="./aaascrape.html" class="no-external">Data Science for Policy Analysts: A Simple Introduction to Web Scraping</a>
</h3>
<div class="listing-categories">

<div class="listing-category" onclick="window.quartoListingCategory('V2ViJTIwU2NyYXBpbmc='); return false;">Web Scraping</div>

<div class="listing-category" onclick="window.quartoListingCategory('UHl0aG9u'); return false;">Python</div>

</div>
</div>
<div class="metadata">
<a href="./aaascrape.html" class="no-external">
<div class="listing-date">
Jan 29, 2025
</div>
<div class="listing-author">
Jared Greathouse
</div>
</a>
</div>
</div>
</div>
<div class="listing-no-matching d-none">No matching items</div>
</div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jgreathouse9\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Jared Greathouse</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script src="js/assumptions.js"></script>




</body></html>