name: Blog Python Code

on:
  push:
    paths:
      - "**"  # Trigger on push to any file in the repository
  workflow_dispatch:

jobs:
  blog-python-code:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r blogcontent/scdense/requirements.txt

    # Run the plotting script
    - name: Run plotting script
      run: python blogcontent/scdense/plotting.py

    # Run the l2est.py script
    - name: Run l2est.py
      run: python blogcontent/scdense/l2est.py

    # Move generated plot to target directory and list files
    - name: Move figure to target directory and list existing files
      run: |
        # List files in the blogcontent/scdense directory before moving the plot
        echo "Listing files in the blogcontent/scdense directory before move:"
        ls -l blogcontent/scdense

        # Create the target directory if it doesn't exist
        mkdir -p blogcontent/scdense/figures

        # Move the plot files to the target directory
        mv blogcontent/scdense/spotapp.png blogcontent/scdense/figures/spottapp.png

        # List files in the target directory after move
        echo "Listing files in the blogcontent/scdense/figures directory after move:"
        ls -l blogcontent/scdense/figures

    # Check if there are any changes to commit
    - name: Check for changes to commit
      run: |
        git status
        git diff --exit-code || echo "There are changes to commit."

    # Commit and push updated figures if there are changes
    - name: Commit and push updated figures
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Add untracked files to Git (if they exist)
        git add blogcontent/scdense/figures/AppleTyla.png || echo "No changes to AppleTyla.png"
        git add blogcontent/scdense/figures/SpotifyTyla.png || echo "No changes to SpotifyTyla.png"

        # Commit the changes only if there are any new files
        git commit -m "Update generated figures: AppleTyla.png, SpotifyTyla.png" || echo "No changes to commit"

        # Push the commit
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
