name: Quarto Presentations

on:
  push:
    branches:
      - master
    paths:
      - 'qprez/**'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the workflow can push changes

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
      
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "1.7.8"

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r qdocs/requirements.txt

    - name: List files in qprez
      run: |
        echo "Listing qprez directory structure:"
        if [ -d "qprez" ]; then
          find qprez -type f -print
        else
          echo "qprez folder not found"
        fi

    - name: Render all Quarto presentations
      run: |
        echo "Rendering all .qmd files in qprez/..."
        qmd_files=$(find qprez -name "*.qmd")
        if [ -z "$qmd_files" ]; then
          echo "No .qmd files found in qprez/"
          exit 0
        fi
        for f in $qmd_files; do
          echo "Rendering $f..."
          quarto render "$f"
        done

    - name: Set up Git configuration
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push rendered content
      run: |
        git fetch origin master
        git reset --soft origin/master
        git add -A
        git commit -m "Rendered Quarto presentation" || echo "No changes to commit"
        git push origin master
