name: Render and Deploy Quarto Presentation

on:
  push:
    branches:
      - master  # Adjust if your default branch is different
    paths:
      - 'Presentations/**'  # Only trigger if files in Presentations/ change

  workflow_dispatch:  # Allows manual triggering

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.8"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Adjust as needed

      - name: Install Python dependencies
        run: |
          pip install -r qdocs/requirements.txt

      - name: Render Quarto Presentation
        run: |
          quarto render Presentations/mlsynthpres.qmd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Presentations/_site  # Adjust if necessary
