name: Quarto Presentations

on:
  push:
    branches:
      - master
    paths:
      - 'qprez/**'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
      
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "1.7.8"

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r qdocs/requirements.txt

    - name: List qprez folder and .qmd files
      run: |
        echo "Listing qprez directory structure:"
        if [ -d "qprez" ]; then
          find qprez -type f -print
        else
          echo "qprez folder not found"
        fi
        echo "Listing .qmd files in qprez:"
        find qprez -name "*.qmd" -print

    - name: Render all Quarto presentations
      run: |
        echo "Rendering all .qmd files in qprez/..."
        quarto render qprez/

    - name: Set up Git configuration
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push rendered content
      run: |
        git fetch origin master
        git reset --soft origin/master
        git add -A
        git commit -m "Rendered Quarto presentations" || echo "No changes to commit"
        git push origin master
