name: Quarto Render

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the workflow can push changes

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "1.7.8"  # Replace with the latest stable version

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy  # Add other Python dependencies as needed

    - name: Render Quarto File
      run: |
        quarto render qdocs/example.qmd  # Adjust this path if needed

    - name: Commit rendered output
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add _site/*
        git commit -m "Render Quarto site"
        git push
