name: Quarto Render with Back Home Link

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the workflow can push changes

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "1.7.8"  # Specify the exact Quarto version

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r qdocs/requirements.txt

    - name: Add "Back Home" link to all .qmd files
      run: |
        for file in qdocs/*.qmd; do
          if ! grep -q "Back Home" "$file"; then
            echo "Adding Back Home link to $file..."
            sed -i '1i[Back Home](https://jgreathouse9.github.io/qdocs/index.html)\n' "$file"
          fi
        done

    - name: Generate index.qmd
      run: |
        echo "---" > qdocs/index.qmd
        echo "title: Blog" >> qdocs/index.qmd
        echo "format: html" >> qdocs/index.qmd
        echo "---" >> qdocs/index.qmd
        echo "" >> qdocs/index.qmd
        echo "[Back Home](https://jgreathouse9.github.io/qdocs/index.html)" >> qdocs/index.qmd
        echo "" >> qdocs/index.qmd
        echo "# Posts" >> qdocs/index.qmd
        echo "Here are my blog posts that cover econometrics, machine learning, and other data science topics." >> qdocs/index.qmd
        echo "" >> qdocs/index.qmd

        # Loop through all qmd files and add links to the index page
        for file in qdocs/*.qmd; do
          if [[ $file != "qdocs/index.qmd" ]]; then
            title=$(grep "^title:" "$file" | cut -d ":" -f2- | xargs)
            link=$(basename "$file" .qmd).html
            echo "1. [$title]($link)" >> qdocs/index.qmd
          fi
        done

    - name: Render all Quarto files
      run: |
        for file in qdocs/*.qmd; do
          echo "Rendering $file..."
          quarto render "$file"
        done

    - name: Check rendered output
      run: |
        ls -l _site/

    - name: Commit rendered output
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add . 
        git diff --cached --exit-code || (git commit -m "Render Quarto site with Back Home link" && git push)
