name: Quarto Blog

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensures the workflow can push changes

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: "1.7.8"  # Specify the exact Quarto version

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r qdocs/requirements.txt

    - name: Generate index.qmd
      run: |
        echo "---" > qdocs/index.qmd
        echo "title: Posts" >> qdocs/index.qmd
        echo "format: html" >> qdocs/index.qmd
        echo "---" >> qdocs/index.qmd
        echo "" >> qdocs/index.qmd
        echo "Here are my blog posts that cover causal inference, econometrics, machine learning, and other data science topics." >> qdocs/index.qmd
        echo "" >> qdocs/index.qmd

    - name: Render all Quarto files
      run: |
        for file in qdocs/*.qmd; do
          echo "Rendering $file..."
          quarto render "$file"
        done

    - name: Check rendered output
      run: |
        ls -l _site/

    - name: Commit rendered output
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add . 
        git diff --cached --exit-code || (git commit -m "Render Quarto site with Back Home link" && git push)
