name: Quarto Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install Quarto
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:quarto/quarto
        sudo apt-get update
        sudo apt-get install -y quarto

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy

    - name: Render Quarto File
      run: |
        quarto render qdocs/example.qmd

    - name: Commit rendered output
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add _site/*
        git commit -m "Render Quarto site"
        git push
