name: Render MLSYNTH Site

on:
  push:
    paths:
      - 'mlsynth/**.qmd'
      - 'mlsynth/_quarto.yml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Install Jupyter and any Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    # 4. Set up Quarto
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: '1.7.8'

    # 5. Render Quarto site in mlsynth folder
    - name: Render Quarto site
      working-directory: mlsynth
      run: quarto render . --no-cache

    # 6. Commit and push generated site
    - name: Commit and push generated site
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-render MLSYNTH site"
        file_pattern: "mlsynth/webdir"
        branch: master
