name: Visa Spending Data Plot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plot_visa_spending:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt

    - name: Run the Visa spending scraper and plotter
      run: |
        python Python/Scrapers/Visa/visamain.py

    - name: Commit and push the Visa spending plot
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Python/Scrapers/Visa/VisaSpending.png
        git commit -m "Add Visa spending plot"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

