name: Visa Spending Data Plot

on:
  schedule:
    - cron: '0 12 16 * *'  # Runs at 12pm EST on the last day of each month
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  plot_visa_spending:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Python/requirements.txt

    - name: Run the Visa spending scraper and plotter
      run: |
        python Python/Scrapers/Visa/visamain.py

    - name: Check if plot was generated
      run: |
        if [ -f Python/Scrapers/Visa/VisaSpending.png ]; then
          echo "Visa spending plot exists."
        else
          echo "Visa spending plot was not generated." && exit 1
        fi

    - name: Remove __pycache__ directories
      run: |
        find . -type d -name "__pycache__" -exec rm -rf {} +

    - name: Commit and push the Visa spending plot
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Ensure Git detects changes, even if the plot is unchanged
        git add -A  # This will stage all changes, including updates to the plot

        # Check if there are any changes to commit
        git diff --cached --exit-code || echo "Changes detected"  # Ignore non-zero exit code
        if [[ -n $(git diff --cached) ]]; then
          git commit -m "Add Visa spending plot"
          git push origin master
        else
          echo "No changes to commit, skipping commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
