name: Visa Plot

on:
  schedule:
    - cron: '0 12 28-31 * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  plot_visa_spending:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Python/requirements.txt

    - name: Run the Visa spending scraper and plotter
      run: |
        python Python/Scrapers/Visa/visamain.py

    - name: Check if plot was generated
      run: |
        if [ -f Python/Scrapers/Visa/VisaSpending.png ]; then
          echo "Visa spending plot exists."
        else
          echo "Visa spending plot was not generated." && exit 1
        fi

    - name: Commit and push the Visa spending plot
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Check for untracked files and only commit if plot exists
        git status
        
        # Add and commit plot if it exists
        if [ -f Python/Scrapers/Visa/VisaSpending.png ]; then
          git add Python/Scrapers/Visa/VisaSpending.png
          git commit -m "Add Visa spending plot"
          git push origin master  # Use 'master' instead of 'main'
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
